### ISSUE TITLE
Implement a Matlab API

### ISSUE THREAD

**Issue by MakisH** [precice/precice#102]
There is an idea to implement a preCICE API for Matlab. For this, we would need to call C/C++ functions from Matlab.

I found that the [coder.ceval](https://de.mathworks.com/help/simulink/slref/coder.ceval.html) can do this, I am not very sure about the implementation though.

Until now there has been at least one potential user that wants to couple their Matlab structure solver with preCICE.

**Comment by BenjaminRueth** [comment]
Just a side remark: MEX Files (see https://www.mathworks.com/help/matlab/matlab_external/introducing-mex-files.html) also provide a MATLAB/C++ interface. Which of the two options is fitting better for implenting a preCICE API for MATLAB, MEX Files or coder.ceval @MakisH, I cannot tell.

**Comment by jy1737** [comment]
I would like to work on this! It seems I'm not allowed to assign myself to this issue though!

**Comment by uekerman** [comment]
@jy1737 I just added you as a collaborator to the repo. Once you accept, you should be able to assign yourself.

**Comment by MakisH** [comment]
Maybe an interesting reading: [Coupling the CTL and Matlab](https://publikationsserver.tu-braunschweig.de/receive/dbbs_mods_00021292).

**Comment by msuaeronautics13** [comment]
I'd like to see this feature, and would like to know what can be done to help.

**Comment by Dominanz** [comment]
An update on this:

I started writing MATLAB bindings [in my fork](https://github.com/Dominanz/precice/tree/develop) since I need them for [my work on TherMoS](https://www5.in.tum.de/wiki/index.php/SC%C2%B2S_Colloquium_-_Dec_20,_2018). They are based on the [C++ MEX API](https://de.mathworks.com/help/matlab/cpp-mex-file-applications.html) introduced in MATLAB R2018a. I will open a pull request once they are in a reasonably clean state (as of now, only a small subset ob the functions is implemented, and I will probably do some changes to the gateway function).

In R2019a (released March 20, 2019), the `clibgen` package was introduced which allows to integrate [C++ libraries seamlessly into MATLAB](https://de.mathworks.com/help/matlab/call-cpp-library-functions.html). This functionality may be the best and easiest way to create MATLAB bindings in the long run (at least I think so). There are some difficulties to be tackled, though. For details, see the new issue #355 opened today.

**Comment by uekerman** [comment]
Great! Thanks for the contribution!

**Comment by Dominanz** [comment]
Note:
As long as #280 remains unsolved, the MATLAB bindings should be [executed out of process](https://de.mathworks.com/help/matlab/matlab_external/out-of-process-execution-of-c-mex-functions.html), or otherwise any error in preCICE will cause MATLAB to crash.
Once #280 is solved, the exceptions can be caught and turned into MATLAB errors.

**Comment by BenjaminRueth** [comment]
Another idea that might be worth investigating: use the [MATLAB/Python Interface](https://www.mathworks.com/products/matlab/matlab-and-python.html) and the preCICE Python bindings instead of a direct MATLAB interface. Why? This might help us get around an issue with MATLAB and MPI.

**Comment by BenjaminRueth** [comment]
Note #409.

**Comment by BenjaminRueth** [comment]
Note https://github.com/precice/precice/issues/366. We should do it right from the very beginning, here.

**Comment by BenjaminRueth** [comment]
#494 will be merged soon

**Comment by BenjaminRueth** [comment]
#494 was merged into https://github.com/precice/precice/tree/draft_MATLAB_bindings. As soon as the bindings are well integrated (test, tutorial, etc.), we will merge this branch into `develop`

**Comment by gilbertolem** [comment]
In #580 there is the PR for merging to develop the work done up to now. The testing procedure is a work in progress. Getting this done the bindings will be well integrated. I think it would be realistic to include the MATLAB bindings in the next release in February.

**Comment by BenjaminRueth** [comment]
The matlab-bindings are now available under https://github.com/precice/matlab-bindings. I added a note on the new bindings in the Changelog: see bdd24e55d6351456826710a87163fff888b82988. This closes the issue.
