### ISSUE TITLE
No package available for Ubuntu 21.04 - Hirsute

### ISSUE THREAD

**Issue by TS-CUBED** [precice/precice#1043]
The documentation refers to a package available for Hirsute Hippo, but there is none on github. 

The last one is Groovy.

**Comment by DavidSCN** [comment]
Thanks for pointing this out. We provided Hirsute packages in the [v2.2.0](https://github.com/precice/precice/releases/tag/v2.2.0) release and it seems we forgot to add them for the following bugfix release. Since the bugfix release covered only some corner cases, you might get along with the v2.2.0 packages until we add them for the bugfix v2.2.1.

**Comment by TS-CUBED** [comment]
Thanks. That'll do for the moment. I had compiled myself, but 2.2.0 will do fine.

**Comment by fsimonis** [comment]
Hi! Just uploaded [the packages](https://github.com/precice/precice/releases/tag/v2.2.1).

**Comment by MakisH** [comment]
Also related to #319
