### ISSUE TITLE
Tooling API

### ISSUE THREAD

**Issue by fsimonis** [precice/precice#1117]
**Please describe the problem you are trying to solve.**

`binprecice` is currently implemented using the xml and config internals. This is ugly and leads to unnecessary dependencies, which in turn makes the CMake configuration ugly and prevents #623.

The clean solution is to implement its functionality as part of the API as stand-alone functions, similar to `precice::getVersionInformation()`. Then `binprecice` could simply rely on the API of preCICE.

**Describe the solution you propose.**

Implement the required functions as stand-alone functions in the API.
Currently, these are:
* Print the configuration reference as XML with annotations.
* Print the DTD file, which can be used to validate XML configuration files.
* Print the markdown version of the reference, which is used for the website.

**Open questions:**

How should we name these functions?
Should we implement them as separate functions or a single function using an enum.
```
// option A
void printConfigAsMD(std::ostream &out);
void printConfigAsDTS(std::ostream &out);
void printConfigAsXML(std::ostream &out);

// option B
enum struct ReferenceType { md, dtd, xml };
void printReference(std::ostream &out, ReferenceType reftype);
```

Should we place these functions in the header `precice/SolverInterface.hpp` or in a new header such as `precice/Tooling.hpp`?
The latter could simplify adding additional tools in the future.

Can we omit these functions from the bindings?
After all, we ship the `binprecice`, which is a convenient way of using these features.

**Comment by uekerman** [comment]
I like the proposed change :+1:

> I personally would prefer to implement the functions independently.
This is easier to use with autocompletion features.
We also won't run into issues for a future format requiring additional arguments.

I would prefer one function, but I am also OK with three.

> I also prefer to place these functions into a separate header.

:+1: This also simplifies the argumentation why we don't port these functions to bindings.

`binprecice` needed for users: Yes, currently makes not too much sense, but could soonish make more sense again. Also the "controller" could one day be part of this:
```
binprecice generate config.yml > config.xml
``` 

> What always bugged me is the name of the executable though. binprecice is just weird.
@uekerman Do you know the rational behind this? Why wasn't it simply called precice, precicecli or similar?

No, not really. This was before my time. I agree that `binprecice` is weird. Simply calling it `precice` is actually interesting.

**Comment by MakisH** [comment]
This is a nice idea!

> Should we implement them as separate functions or a single function using an enum.

I guess this is a common problem. While I find the `enum` option more elegant (it maybe avoids some duplication), I agree that the individual functions are maybe easier or more robust. In any case, I don't much how too much could change in the future in this aspect, so just go with whatever you feel more comfortable with right now.

> Should we place these functions in the header `precice/SolverInterface.hpp` or in a new header such as `precice/Tooling.hpp`?

If we don't want to include them in the bindings, then leaving them out of `SolverInterface.hpp` sounds like the right thing to do.

I guess we would then not need to distribute `Tooling.hpp` with any packages, as no other code is meant to use them.

> I would also omit these functions from the bindings to reduce unnecessary maintenance.

Yes, the bindings are already complex enough as they are (especially since they are many).

I really like how we can actually add useful functionality in `binprecice`. The version, the check, the formatting, even potentially the visualizer, all would be so much nicer to have discoverable via one standard tool.

Regarding the name I agree that `binprecice` is weird (and that it currently is not easy to guess what this is for), `precice-cli` sounds reasonable to me, as well as `precice-tools` or so. I downvote just `precice`, as it could create a lot of confusion on what this is and if this is the right thing to look for.
