### ISSUE TITLE
Incorrectly named vtu piece files.

### ISSUE THREAD

**Issue by fsimonis** [precice/precice#1125]
**Describe your setup**

Operating system: Arch
preCICE Version: 2.3.0

**Describe the problem**

The exported parallel unstructured grid files are incorrectly named. This could also explain #226.

| | main | piece |
--- | --- | ---
preCICE | `NAME_master.pvtu` | `NAME_rN.vtu`
VTK | `NAME.pvtu` | `NAME_N.vtu`

Using the correct naming scheme also allows to import all timestep `dtN.pvtu` files  as a group into Paraview.
This then allows to use step through the _time_ directly in Paraview. 

**Step To Reproduce**
1. Configure a parallel participant to export a mesh
2. Run the simulation
3. Look at the filenames

**Expected behaviour**
The preCICE vtk exporter should correctly name piece and main files.

**Additional context**
https://github.com/precice/aste/issues/38

**Questions**

If we consider this a bug, will this change then be breaking?

**Comment by MakisH** [comment]
Is this grouping described somewhere in the ParaView or VTK documentation? If we change it, we should make sure that we do it "right" and that there is a good reason to change it.

If this is indeed a bug (i.e., something is not working as expected because of this), then I think it should be fine not considering it breaking.

In principle, I like the idea, the naming scheme also feels more natural: why should we differentiate `master` from any other rank? And if `master` does not refer to the rank, then it is more confusing altogether.

**Comment by fsimonis** [comment]
> In principle, I like the idea, the naming scheme also feels more natural: why should we differentiate master from any other rank? And if master does not refer to the rank, then it is more confusing altogether.

The master file has indeed nothing to do with the master (as in rank 0). As you said, it's confusing.

**Comment by uekerman** [comment]
> If this is indeed a bug (i.e., something is not working as expected because of this), then I think it should be fine not considering it breaking.

:+1:

**Comment by DavidSCN** [comment]
> Removing the _master enables the grouping in Paraview.

I would also vote for a non-breaking change. Let's fix this as soon as possible.

**Comment by fsimonis** [comment]
Great. On it.
