### ISSUE TITLE
Replace std::vector with std::map for storing meshes and data (and other?)

### ISSUE THREAD

**Issue by BenjaminRodenberg** [precice/precice#1165]
Currently we use `std::vector` very often as a container for storing meshes and data. The mesh or data is then queried via its id. I think using a `std::map` would be more appropriate for this use-case, because we do not have to reserve memory beforehand, keys are still unique by definition of the data structure and we need less checks ([example](https://github.com/precice/precice/blob/8a4f4845f544a6c2a11f45e4b92ebd96874f4456/src/precice/impl/Participant.cpp#L244-L245)).

### Current use of `std::vector`

1. Initialize an `std::vector` as a container:

https://github.com/precice/precice/blob/8a4f4845f544a6c2a11f45e4b92ebd96874f4456/src/precice/impl/Participant.cpp#L29

2. Store something at the corresponding ID:

https://github.com/precice/precice/blob/8a4f4845f544a6c2a11f45e4b92ebd96874f4456/src/precice/impl/Participant.cpp#L95

3. Query via ID:

https://github.com/precice/precice/blob/8a4f4845f544a6c2a11f45e4b92ebd96874f4456/src/precice/impl/Participant.cpp#L242

### Proposed use of `std::map`

I'm currently working on https://github.com/precice/precice/pull/1159, where `_readDataContext` and `_writeDataContext` will be stored in a `std::map`:

https://github.com/precice/precice/blob/8d17471d1fa1c1f42075971d1b398b86c0d28d33/src/precice/impl/Participant.hpp#L298-L300

Previously, a `std::vector` (see also #1164) was used:

https://github.com/precice/precice/blob/8a4f4845f544a6c2a11f45e4b92ebd96874f4456/src/precice/impl/Participant.hpp#L311-L315

**Comment by DavidSCN** [comment]
I would vote against this change, simply because a `std::vector` is just a much more efficient data structure compared to a `std::map`, especially for small data structures as present here. A map has higher memory requirements and (depending on the overall size) much worse look-up times. Does it matter here? I'm not sure, but I'm not really convinced by the arguments presented:

> because we do not have to reserve memory beforehand, 

If you have the option to reserve memory beforehand, it is a good idea to do so. If you run out of memory, one can still use `emplace_back` or something similar in order to extend the memory. `Data` and `Mesh` are anyway quite static once initialization finished.

> and we need less checks 

I think it would be a good idea to check similar things for a map (for example the `nullptr`). I don't know the resulting error message from a missing (or invalid key), but it might be a good idea to check it beforehand in order to spot the issue right ahead.

To conclude my opinion: why changing to a slower alternative for no good reason?

**Comment by BenjaminRodenberg** [comment]
> To conclude my opinion: why changing to a slower alternative for no good reason?

I don't agree. Performance is not the issue here. These datastructures are mainly used for storing and passing around references, not for performance-critical operations. I found using them extremely inconvenient and using a vector for a use-case where a map is the right data structure (we *map* IDs to values) does not make sense.

**Comment by fsimonis** [comment]
> The main critical argument in favor of this change is that currently we misuse the IDs as indices. There is not guarantee that the IDs are numbered from 0 to n-1. They just happen to be right now, but this could change in the future if we change the ID management at some point.

This is the main issue and I already ran into this plenty of time.

We essentially need some sort of associative container. `std::vector` currently works, but it is problematic and bugprone.

As these indexing structures are not performance-critical, I would  vouch for `std::map` until we have a reason to choose something else.
If performance becomes an issue at some point, we can always experiment with `boost::container::flat_map` or even unordered maps.

**Comment by fsimonis** [comment]
Related to #1461

**Comment by BenjaminRodenberg** [comment]
@fsimonis this issue should be solved by now. I found this here recently:

https://github.com/precice/precice/blob/665c3d3652dab6a39770b34ee88acb1a7c6550bd/src/precice/impl/ParticipantState.hpp#L333-L337

**Comment by fsimonis** [comment]
Thanks for the bump.
I checked the code base and cannot find another instance of this.
