### ISSUE TITLE
Multiple read mappings to same mesh assign wrong mappingContext to dataContext

### ISSUE THREAD

**Issue by uekerman** [precice/precice#1204]
**Describe your setup**

Current preCICE develop version

**Describe the problem**

When we allowed multiple read mappings to the same mesh in #849, we forgot to update the following assignment (which still assumes that there is only one read mapping to a certain mesh). 

https://github.com/precice/precice/blob/ebce55ab5c563295909b0179f6610b6e4d4fa529/src/precice/config/ParticipantConfiguration.cpp#L517-L534

A user ran into this problem: 

https://precice.discourse.group/t/participant-reads-zeros-for-mapped-data/994/9

(simplified) preCICE config:

```xml
    <mesh name="Fluid1-Centroids">
      <use-data name="Density-f2" />
      <use-data name="Velocity-f2" />
      <use-data name="Pressure-f2" />
    </mesh>

    <mesh name="Fluid2-Centroids">
      <use-data name="Density-f2" />
      <use-data name="Velocity-f2" />
    </mesh>

    <mesh name="Fluid2-Nodes">
      <use-data name="Pressure-f2" />
    </mesh>

    <participant name="Fluid1">
      <use-mesh name="Fluid1-Centroids" provide="yes" />
      <use-mesh name="Fluid2-Centroids" from="Fluid2" />
      <use-mesh name="Fluid2-Nodes" from="Fluid2" />

      <read-data name="Density-f2" mesh="Fluid1-Centroids" />
      <read-data name="Velocity-f2" mesh="Fluid1-Centroids" />
      <read-data name="Pressure-f2" mesh="Fluid1-Centroids" /> 

      <mapping:nearest-neighbor
        direction="read"
        from="Fluid2-Centroids"
        to="Fluid1-Centroids"
        constraint="consistent" />
      <mapping:nearest-projection
        direction="read"
        from="Fluid2-Nodes"
        to="Fluid1-Centroids"
        constraint="consistent" />
    </participant>
[...]
```

Error message

```
(0) 10:09:48 [config::ParticipantConfiguration]:529 in finishParticipantConfiguration: ERROR: Mesh “Fluid2-Nodes” needs to use data “Density-f2” to allow a read mapping to it. Please add a use-data node with name=“Density-f2” to this mesh.
```

Obviously, this error message is wrong, but more concerning is that also the assignment

https://github.com/precice/precice/blob/ebce55ab5c563295909b0179f6610b6e4d4fa529/src/precice/config/ParticipantConfiguration.cpp#L531

is wrong.

**Step To Reproduce**

Let's try to reproduce the problem with an integration test. A copy of this one should be a good starting point:

https://github.com/precice/precice/blob/ebce55ab5c563295909b0179f6610b6e4d4fa529/src/precice/tests/SerialTests.cpp#L2926

**Additional context**

Of course, we have the same problem for multiple **write** mappings **from** the same mesh.

**Comment by BenjaminRodenberg** [comment]
I assume this worked before I started refactoring the `DataContext`. So essentially https://github.com/precice/precice/commit/f1e4a0f442d03657fe40d14e76ec7bcecdd8c49b would be a good candidate to check. Note that there are a few more iterations down the road: 
1. https://github.com/precice/precice/pull/1038 (already part of v2.3.0)
2. https://github.com/precice/precice/pull/1159
3. https://github.com/precice/precice/pull/1187 (but this was merged after this issue was opened)

My assumption when working on `DataContext` was that a data context holds a single mapping context. As far as I understand this is not true, if there are multiple mappings. I'm not sure how this worked before, but I'm also not so deep in the mapping business. If fixing this issue requires to extend the functionality of `DataContext`, I think a corresponding unit test in https://github.com/precice/precice/blob/develop/src/precice/tests/DataContextTest.cpp would help a lot.
