### ISSUE TITLE
Tag use-mesh has too many purposes. 

### ISSUE THREAD

**Issue by fsimonis** [precice/precice#1294]
**Please describe the problem you are trying to solve.**

The `use-mesh` tag currently means two things:
1. use this mesh from another participant (`provide="false" from="X"`)
2. provide this mesh to the simulation (`provide="true")

This has two downsides:
* both tags look the same, while they do fundamentally different things.
* one tag to handle both "directions" is inconsistent with how we handle data, where we have two different tags `read-data` and `write-data`.
* there is an increasing amount of state that only makes sense for one use-case:
  For provided meshes, `from` and `direct-access` don't make sense.
  For used meshes, potentially `adaptive` #1293 won't make sense. 

**Describe the solution you propose.**

As this is configuration-only, both suggestions can be implemented without breaking backwards-compatibility.

Suggestion 1: Add `provide-mesh` for ... providing a mesh _(DUH)_

```xml
<use-mesh name="mesh" from="there" safety-factor="0.5" geometric-filter="on-secondary-ranks"  direct-access="0"/>`
<provide-mesh name="{string}" />
```

Suggestion 2: Split `use-mesh` into `provide-mesh` and `receive-mesh`

This also reads more naturally: 

> I provide mesh A.
> I receive mesh A from P. (Even though I really need an exchange tag for that)

```xml
<receive-mesh name="mesh" from="there" safety-factor="0.5" geometric-filter="on-secondary-ranks" direct-access="0"/>`
<provide-mesh name="{string}" />
```

**Describe alternatives you've considered**

Leave it as is or move towards a tag-heavy style #1236 

_edit: removed attributes in provide-tags that only apply to use-tags_

**Comment by uekerman** [comment]
I share your observation in principle. Many of the attributes you use above are actually only meaningful for received meshes (`geometric-filter`, `safety-factor`).
To have a really clean cut, I would favor suggestion 2. 
Spontaneous idea: `set-mesh` instead of `provide-mesh`? Then there could be an easy-to-understand alignment with the API (`setMeshVertex`, ...). (not sure about this yet)

> Even though I really need an exchange tag for that

Exchange tags are for exchanging data. Meshes are exchanged with these tags. In principle, there is a clean logic here (if the user understands it ... it's certainly one of the more complicated things to learn).

I am bit afraid however that implementing this without breaking backwards compatibility will be a checking-state nightmare. But simply breaking such things with v3 should be a valid option, no?

**Comment by fsimonis** [comment]
Ah right about the exchange tags.
I don't want to end up in the exchange tags vs read-data and write-data discussion though.

Naming is important and I always disliked using `set` as it is one of the least specific verbs in the English language and it can even be confused with the noun.

I would definitely strive for something more expressive:

* provide-mesh
* expose-mesh
* define-mesh
* register-mesh
* send-mesh
* broadcast-mesh
* produce-mesh

We could also use a noun like source or origin, but this isn't consistent with the data tags.

For the use side:

* receive-mesh
* consume-mesh
* handle-mesh
* access-mesh
* request-mesh
* utilise-mesh
* require-mesh
* source-mesh

**Comment by fsimonis** [comment]
@uekerman and I converged towards provide-mesh and receive-mesh.
