### ISSUE TITLE
First Steps Waveform Relaxation / Subcycling

### ISSUE THREAD

**Issue by BenjaminRodenberg** [precice/precice#133]
Below you find a sketch on a feature idea. The sketch is based on the [elastictube1d example](https://github.com/precice/elastictube1d), where pressure (p) and cross section area (a) are coupled to simulate an elastic tube with fluid flow. On long term we want to allow high order time integration with subcycling inside preCICE using waveform relaxation. 

This issue is a first step in this direction. We want to perform a linear interpolation inside preCICE. This helps, if provided data by one participant is not sufficient (for example due to subcycling).

A first experimental implementation going into this direction can be found in https://github.com/precice/elastictube1d/blob/convergenceStudies/PythonTube/FluidSolver.py lines 131-134.

![grafik](https://user-images.githubusercontent.com/5740604/42563903-af978808-84ff-11e8-9c29-ca624721221d.png)

**Comment by BenjaminRueth** [comment]
somehow related: https://github.com/precice/precice/issues/149

For waveform relaxation we have to be able to exchange multiple (arbitrarily many) pieces of data per interface grid node per timestep. This is not supported by the currently existing API functions. Currently we can only exchange one double per grid node using `Send/WriteBlockScalarData` (scalar quantities like temperature) or `dim` doubles per grid node using `Send/WriteBlockVectorData` (vector valued quantities like velocity).

Sending more than `dim` values using `Send/WriteBlockVectorData` might be a possibility, but to my understanding this is not the correct use of the API and this function should be reserved for vector values (physical) quantities. Another reason, for not using an array to send multiple data values per interface grid node: For vector data index computation becomes vulnerable to error.

**Comment by uekerman** [comment]
We collected four ways how to tackle waveform relaxation in preCICE:

(1) **Adapter Variant**: Construct higher-order polynomials in the adapter by misusing preCICE and exchanging multiple data values. Not use `VectorData` as above, but simply using many data values. This is no problem as we know a-priori how many we need if the solvers do not use adaptive timestep sizes. All this is hacky, but this is only a first step to have more testcases. @BenjaminRueth is looking into that. Of course, no changes to the API are necessary.

(2) **Black-box Variant**: preCICE constructs higher-order polynomials from pure black-box data. For the solvers everything seems like before, just as subcycling, but with better data. No changes to the API are necessary. We do not know yet how to do this numerically in a general way, but linear polynomials are not complicated to do. I will implement a first and document in this issue. 

(3) **Exchange Polynomials**: Instead of nodal values in time, the solvers give functions (or approximations) to preCICE. API changes are necessary.

(4) **Request Values**: Each solver gives a list of timesteps, where he requires data values. preCICE gives this list to the other side. API changes are necessary.

**Comment by BenjaminRueth** [comment]
I did some experiments with approach (1). Here a short status update:

* I did not measure the order, but conceptually it works. My test case, where I compare the "non-preCICE-version" to the one with preCICE completes successfully.
* Depending on the number of subiterations for each participant, we need **specialized** config files. Example: if we have 5 subiterations, we have to define `Temperature0, Temperature1, ... Temperature5`. For 10 subiterations we only need `Temperature0, Temperature1, ... Temperature10` and so on. This is really ugly.
* However, we can use the same adapter for arbitrary number of subiterations.

**Comment by BenjaminRueth** [comment]
One thing that cost me a lot of time in my experimental Python code today: I do not use a proper data format for waveforms yet. Especially when you interpolate from one temporal grid onto another this can lead to many problems. We should carefully think about a good format. 

In my Python code I now ended up with `lists` of `np.ndarrays`. Each list entry represents one sample in time. Therefore, the list has `n_substeps + 1` elements. The `np.ndarray` holds the data on the interface and can directly be used with the preCICE API calls `writeBlockScalarData` and `readBlockScalarData`.

**Why not use a big `np.ndarray` for everything?** Taking slices from the array was from my perspective not robust enough. It is very easy to mess up the shape of the array, if you do not take care and this makes some trouble in your linear algebra later.

**Comment by uekerman** [comment]
With the last comment you mean concatenating all temperatures into one coupling data `Temperature` instead of `Temperature1`,`Temperature2`, ... ?
Then, the config is independent from amount of small timesteps. We lose, however, the possibility to only use the latest values in the QN and similar things.

Btw, I just pushed a very simple first class. Next steps will be to make this configurable and do integration tests (only for serial-explicit first). 

I decided for the moment to not hold coupling data in the interpolation class, everything is still in `CouplingData`. There, we could also access values from previous timesteps. It could be that eventually we need sth more complicated.

**Comment by BenjaminRueth** [comment]
This is a slightly different approach to waveform relaxation: https://github.com/PeterMeisrimel/asynch-WFR

**Comment by BenjaminRueth** [comment]
Related: https://github.com/precice/fenics-adapter/pull/35 and https://github.com/precice/tutorials/pull/30

**Comment by BenjaminRueth** [comment]
In the following a short implementation draft inspired by the [current state here](https://github.com/BenjaminRueth/precice/blob/f094f1f6905016c9cb310660c097954b1653e168/src/cplscheme/BaseCouplingScheme.cpp#L297-L315):

```
  // store data that was provided by writeBlockScalarData into waveform buffer
  if (subcyclingIsCompleted()) {
    // advance needs to work on a different datastructure in the future (-> waveform buffer)
    if (isExplicitCouplingScheme()) {
      explicitAdvance();
    } else if (isImplicitCouplingScheme()) {
      implicitAdvance();
    }
    // note that we have to send/receive several samples in time per window
  }
  // interpolate data using waveform buffer and update data provided by readBlockScalarData (has to be called after advance! Otherwise we do not know which data is needed.)  
```

**Comment by BenjaminRodenberg** [comment]
Closing this issue, because we are now far beyond the first steps. @uekerman feel free to reopen, if you think we still need this kind of overview issue. (could rename it and provide an update etc.)
