### ISSUE TITLE
Put events at appropriate places and come up with naming convention 

### ISSUE THREAD

**Issue by uekerman** [precice/precice#135]

**Comment by floli** [comment]
Some conclusions from the phone call with @uekerman 

* Naming scheme: Oriented at package names, like `map.pet.fillMatrixA`
* Where: at least at all relevant steering functions, such as `configure, initialize, initializeData, advance`
* Scoping/Prefix: Events at these functions should set up a prefix scope, like `  utils::ScopedEventPrefix sep("initialize/");` The resulting event name is now `initialize/map.pet.fillMatrixA`. A slash is used as delimiter instead of period, so that code location (`.`) can be distinguished from call stack location (`/`)
* Currently all these Events also act as a barrier (unless testMode is active). Since Events are logged for all ranks, and maximum times can be computed by post-processing tools, that barrier might not be necessary anymore.
* There is the `M2N_PRE_SYNCHRONIZE` ifdef. It forces synchronization of both masters before data exchange of interface data starts and is usually not active. This _barrier_ is realized using a ping-pong send-receive. The ifdef should maybe replaced a by a `precice::syncMode` (like testMode) that enables various synchronization points and thus easing debug or log file interpretation.
* Also the ping-pong for synchronization can be replaced by a proper barrier. First tries still dead lock, I will put my efforts in a separate branch, and everybody is invited to hack on it.

Any comments appreciated!

**Comment by uekerman** [comment]
I adjusted all events and added/removed a few.
https://github.com/precice/precice/commit/67000eb31676329b590d72c85da06f3bd7b252ee

I also added a `solver.initialize` event which is quite handy to compare the init costs of preCICE to the solver's. 

`precice::syncMode` could also be used for the intra-participant barrier. I think, there is no real usecase, where we only want a barrier intra, but not inter. 

You have to careful, though, such a barrier does not work for `configure` and `finalize` as part of the sync happens before `MPI_Init` resp. after `MPI_Finalize`.

**Comment by floli** [comment]
Good job!

So most Events should get a barrier at start/stop when `syncMode` is enabled?

**Comment by floli** [comment]
Ok to merge?

**Comment by floli** [comment]
Outcome of discussion: The barrier argument to an `Event` should generally be `precice::syncMode` if synchronization is needed to get accurate measurements.

Reason: Most explicit, least surprising to developer than an implicit global default. Still the user should be able to deactivate all synchronization to max preCICE out.

**Comment by uekerman** [comment]
https://github.com/precice/precice/commit/bfb5424e38456ddcc3679583ec48c1b639ac5535
