### ISSUE TITLE
precicef_mark_action_fulfilled(writeInitialData) is missing in examples/solverdummies/fortran/solverdummy.f90?

### ISSUE THREAD

**Issue by gdenayer** [precice/precice#1365]
**Describe your setup**

Operating system (e.g. Linux distribution and version): CentOS 7
preCICE Version: 2.4.0

**Describe the problem**
In order to couple my fluid solver with preCICE, I'm using examples/solverdummies/fortran/solverdummy.f90 as second solver.
I add initialize="yes" to my exchange line in my xml file and I'm getting:

 DUMMY: Writing initial data
---[precice] ERROR:  Initial data has to be written to preCICE by calling an appropriate write...Data() function before calling initializeData(). Did you forget to call markActionFulfilled(precice::constants::actionWriteInitialData()) after writing initial data?

It seems that  precicef_mark_action_fulfilled(writeInitialData) is missing.

**Step To Reproduce**
1.  add initialize="yes" to the xml file
2. then compile and start solverdummy.f90

**Expected behaviour**
No Error :)

**Additional context**
Modifying examples/solverdummies/fortran/solverdummy.f90 as follows solves this issue:
  CALL precicef_is_action_required(writeInitialData, bool)
  IF (bool.EQ.1) THEN
    WRITE (*,*) 'DUMMY: Writing initial data'
    CALL precicef_mark_action_fulfilled(writeInitialData)
  ENDIF
  CALL precicef_initialize_data()

Please note that the different solverdummies seem not to be equivalent.  The section "writeInitialData" is present in solverdummy.f90 but not in solverdummy.c and in  solverdummy.cpp

Regards
Guillaume

**Comment by BenjaminRodenberg** [comment]
Hi @gdenayer,

thanks for pointing us to this issue! The fix that you prepared looks correct. I think that originally data initialization was not part of the solverdummies, but generally it does not harm to add this. I also realized that the implementation of the fortran solverdummy definitely has a problem: https://github.com/precice/precice/blob/c9095ee9f8feceb938e3f9dd8ad6fd55e56a6609/examples/solverdummies/fortran/solverdummy.f90#L68-L71

Actually no data is written.

If you want, feel free to [open a Pull request](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-a-pull-request) that includes your fix. I also realized that data initialization is missing for the C++ and C version of the solverdummies ([here](https://github.com/precice/precice/blob/develop/examples/solverdummies/cpp/solverdummy.cpp) and [here](https://github.com/precice/precice/blob/develop/examples/solverdummies/c/solverdummy.c)).

Side remark 1 (mostly to @gdenayer): It might also be interesting to use one of the existing tutorial for your experiments. You could, for example, use the [perpendicular flap](https://github.com/precice/tutorials/tree/master/perpendicular-flap). Another possibility is to use [ASTE](https://github.com/precice/aste) to provide dummy data.

Side remark 2 (mostly internal): This issue is related to https://github.com/precice/precice/issues/1196, because the solverdummies will need another update with preCICE `v3.0.0`.

**Comment by gdenayer** [comment]
Hi @BenjaminRodenberg,

Thx for your quick reply. Yes, indeed no initial data is written. For me the major issue here is that the 3 different solverdummies are not equivalent. All 3 solverdummies should include the data initialization or all 3 solverdummies should remove it.

It seems that this issue will be solved in preCICE v3.0.0 if the data initialization is mandatory...

Thx for your advice. For the moment I'm only playing with preCICE trying to understand how it works. Therefore the solverdummies are very useful. The validation step is for later.

Have a nice day

**Comment by davidscn** [comment]
Was resolved by #1487
