### ISSUE TITLE
Rename SolverInterface?

### ISSUE THREAD

**Issue by uekerman** [precice/precice#1458]
As we are breaking, we could open the box and discuss whether it makes sense to rename `SolverInterface`.

I always found the name confusing, what is it an interface for / to? From user perspective it is an interface or a handle to preCICE. Or should it be an interface to the other solver? From dev perspective, it is also does not really represent a solver ... especially as we also have the `Participant` class. An "interface to solver" sounds a lot like a framework approach.

Why not calling it `Precice`? (other than the ugly spelling)
When explaining preCICE and in many integration tests, we call the object `precice` anway

From [step-by-step guide](https://precice.org/couple-your-code-steering-methods.html):

```cpp
precice::SolverInterface precice("FluidSolver","precice-config.xml",rank,size);
```

What about the name of the header? I think back in the day, it made sense to not call it `precice.hpp` as we had multiple objects (`Constants`, `MeshHandle`, and `SolverInterface`), but now we only have one header to include.

Opinions?

It would also mean that we rename the configuration, see also #1416.

**Comment by davidscn** [comment]
Upvote, also the header renaming. Note that this is only somewhat breaking, we can always add a redirect from old names to updated names in order to enforce compatibility.

**Comment by uekerman** [comment]
Thinking of #655 I could make more sense to call the object `Participant`.

**Comment by BenjaminRodenberg** [comment]
We should merge https://github.com/precice/precice/pull/1366 before starting to work on this, because otherwise rebasing #1366 will be a nightmare. Then we can also directly break it. I would not worry about redirections, because this introduces additional code that just exists for maintaining legacy.

On the actual issue: I agree. I don't like `SolverInterface`, as well. Be aware that there is already a `precice::impl::Participant`. In some of our tutorials we simply call it [`interface`](https://github.com/precice/tutorials/blob/eaf55b17ae88f8b37c20ae8791467f16ed1e2f0e/elastic-tube-1d/solid-cpp/src/SolidSolver.cpp#L28) or [`Adapter`](https://github.com/precice/tutorials/blob/eaf55b17ae88f8b37c20ae8791467f16ed1e2f0e/partitioned-heat-conduction/fenics/heat.py#L103).

I generally like the idea of calling the header `precice.hpp`. We already do something similar in the python bindings ([`import precice`](https://github.com/precice/tutorials/blob/eaf55b17ae88f8b37c20ae8791467f16ed1e2f0e/elastic-tube-1d/solid-python/SolidSolver.py#L7)). We could also call the object `Precice`, but this will introduce capitalized `P`s everywhere :see_no_evil:

How do other libraries solve this?

* `MPI`, for example, does not provide an object for interfacing with the library (different situation), but the communicator (`COMM_WORLD` etc. maybe has a similar role).
* When interacting with a database the situation is somehow similar: Here the library returns a [`Connection` object](https://www.geeksforgeeks.org/sql-using-python/).

**Comment by fsimonis** [comment]
We should definitely provide `precice/precice.hpp` as a central header.
This allows us to freely split up the content and include it from there.

From the user-perspective, the created instance is a `precice::Participant`, not some kind of interface. Renaming the class alone will make many error messages regarding participants way clearer, as code, configuration, and messages all use the same vocabulary.

Backwards compatibility won't be a big issue.
We could even use a deprecated type alias `[[deprecated]] using SolverInterface = precice::Participant;`. I would just remove it though as we are breaking.

#1416 is tricky. As mentioned above, the user creates a Participant, which corresponds to the participant tag in the configuration. The `solver-interface` tag never really lined up with the usage of the library.
Hence, I would consider renaming the `SolverInterface` to `Participant` a fix.

**Comment by MakisH** [comment]
I also upvote this, and I really like the `precice::Participant` name. It makes a lot of sense since the constructor defines a (rank of a) participant.

Let's generally avoid everything the user interacts with as `precice` (API, bindings, adapters, configs, ...). I am afraid this will be very confusing. :see_no_evil:

**Comment by fsimonis** [comment]
To conclude, we need to

* Add `precice/precice.hpp` as central include
* Rename `precice/SolverInterface.hpp` to `precice/Participant.hpp` (same for Impl)
* Rename `precice::SolverInterface` to `precice::Participant` (same for Impl)

Open question: What do we do with `precice::impl::Participant`?

**Comment by BenjaminRodenberg** [comment]
> Open question: What do we do with `precice::impl::Participant`?

Is it a real problem? It lives in a different namespace, so technically there is no problem, correct? If the name `Participant` fits for what `precice::impl::Participant` is doing it's ok. It might be confusing in certain situations and therefore not ideal, but I would consider this a different issue and not start renaming `precice::impl::Participant` in this issue.

**Comment by fsimonis** [comment]
> edit I oversaw the (same for Impl) comment above. Having precice::Participant, precice::ParticipantImpl and precice::impl::Participant might indeed be a bit too much...

`SolverInterfaceImpl` lives in `precice::impl`. :sweat_smile: 

So it's even worse: `precice::Participant`, `precice::impl::ParticipantImpl` and `precice::impl::Participant`

**Comment by fsimonis** [comment]
Follow-up question regarding the Fortran and C language bindings:

Should we also add this central include for those variants?
```
precice.hpp
preciceC.h
preciceFortran.h
```

**Comment by davidscn** [comment]
Discussing in person.

- we want to rename the headers as described above https://github.com/precice/precice/issues/1458#issuecomment-1341021064
- we want to rename the `SolverInterface` class to something intuitive for the user, namely `precice::Participant`. One argument for the `SolverInterface` name was the association to the `<solver-interface>´ tag in our xml file. However, there is no intuitive meaning of this tag for our users. Hence, we want to get rename it to something more generic (e.g., `scenario`, `simulation`, `simulation-setup`), which doesn't match the name of the preCICE class anymore. If we find out (in the process of applying the changes) that there is no clear meaning of the tag at all, we can also remove it completely. 

Example xml for renaming the tag

```xml
<?xml version="1.0" encoding="UTF-8" ?>
<precice-configuration>
  <log>
    ...
  </log>

  <simulation-setup dimensions="2" experimental="true">
    <data:vector name="Force" />
     ...

    <participant name="Fluid">
      <provide-mesh name="Fluid-Mesh" />
       ...
    </participant>

    <m2n:sockets from="Fluid" to="Solid" exchange-directory=".." />

    <coupling-scheme:parallel-implicit>
      <time-window-size value="0.01" />
       ...
    </coupling-scheme:parallel-implicit>
  </simulation-setup>
</precice-configuration>
```
 Example xml for removing the tag (this doesn't imply any conclusion on #1466)

```xml
<?xml version="1.0" encoding="UTF-8" ?>
<precice-configuration dimensions="2" experimental="true">
  <log>
    ...
  </log>

    <data:vector name="Force" />
     ...

    <participant name="Fluid">
      <provide-mesh name="Fluid-Mesh" />
       ...
    </participant>

    <m2n:sockets from="Fluid" to="Solid" exchange-directory=".." />

    <coupling-scheme:parallel-implicit>
      <time-window-size value="0.01" />
       ...
    </coupling-scheme:parallel-implicit>
</precice-configuration>
```

**Comment by uekerman** [comment]
What is missing are still decisions on how to rename the classes in preCICE. Suggestion:

- `SolverInterface(Impl)` -> `Participant(Impl)`
- `Participant` -> `ParticipantState`

**Comment by MakisH** [comment]
When renaming the `SolverInterface` class to `Participant`, what do we want to do with the `SolverInterface.hpp` file?

- Rename it to `precice.hpp` (makes sense from the user side) https://github.com/precice/precice/issues/1458#issuecomment-1341021064
- Rename it to `Participant.hpp` (consistency with the class name)

**Comment by davidscn** [comment]
My understanding of the conclusion was:

- `SolverInterface(Impl)` -> `Participant(Impl)`
- `SolverInterface(Impl).xpp` -> `Participant(Impl).xpp`
- `Participant` -> `ParticipantState`
- `Participant.xpp` -> `ParticipantState.xpp`

`precice.hpp` will become a central include for all preCICE related include files, which comprises at least `export.h`, `Participant.h`, `Version.h`, `span.hpp`, etc..

The file will most likely look like

```cpp
#pragma once

#include <Participant.hpp>
#include <Version.h>
#include <span.hpp>
...
```

**Comment by uekerman** [comment]
I think we did everything necessary here, right, @MakisH ?
If not, please re-open.
