### ISSUE TITLE
Implement and test Quads

### ISSUE THREAD

**Issue by floli** [precice/precice#153]
Right now, Quads (hexahedrals) are implemented, but not throughout preCICE and not really tested.

**Comment by msuaeronautics13** [comment]
I am interested in this feature for accurate face pressure to nodal force mapping on quads.

**Comment by fsimonis** [comment]
After recent refactoring, this issue boils down to implementing the following function:
https://github.com/precice/precice/blob/dc8c6ddbc2c2a48d92ff53302bdd9fd9ae9c05ef/src/math/barycenter.cpp#L194

**Comment by BenjaminRueth** [comment]
Generally, we cannot assume that all Quads are planar. This makes everything a bit more complicated than with interpolation on triangles. For planar Quads everything is more or less the same like with triangles. 

So how can we deal with non-planar Quads? We have three options:

* **Option 1:** Don't deal with non-planar Quads, but throw an error. If a user provides a mesh with non-planar Quads we just do not support this mesh.
* **Option 2:** Convert all Quads to triangles and perform interpolation in the resulting triangle mesh.
* **Option 3:** Perform interpolation on non-planar Quads.

Either of the aforementioned options leads to some follow-up-problems:

## Option 1:

* **Problem 1.1:** How can we determine whether a Quad is planar or not?
* **Problem 1.2:** Within which tolerance do we consider a Quad planar?

## Option 2: 

* **Problem 2.1:** Splitting a Quad into two triangles is not unique (which of the two diagonals do we take?). 
* **Problem 2.2:** Splitting a Quad into four triangles requires a fifth point, where the four triangles meet (how do we determine this point?).

## Option 3:

* **Problem 3.1:** Interpolation on a non-planar Quad is expensive, since we have to solve a non-linear optimization problem to do this.

A useful approach to some of the problems mentioned above might be to create a plane that is a least squares fit to the actual non-planar quad. The rought methodology is described [here](https://math.stackexchange.com/questions/2810048/plane-fitting-using-svd-normal-vector). 

Creating this least squares fit first provides us with an estimate for the error introduced by using a plane instead of a non-planar Quad (Problem 1.1 and 1.2). To me it looks less arbitrary than both approaches for splitting a Quad into triangles. Finally, we can also use the least squares fit plane for projection, which is much cheaper than solving the non-linear optimization problem (Problem 3.1). Of course, we introduce an error here, but since we can estimate the error (and in case the estimated error is too high fall back to solving the non-linear optimization problem), this is not too bad.

**Comment by JurgenKersschot** [comment]
I am also interested in this feature for consistent mapping of pressures at the nodes of a triangle to the nodes of a quad (90° corners); normal velocities will be mapped consistently in the other direction. Plane quads would suffice (plate elements); if possible, curved quads (shell elements) would be very interesting as well.
