### ISSUE TITLE
Confusing fall-back warnings in linear-cell interpolation

### ISSUE THREAD

**Issue by davidscn** [precice/precice#1565]
**Describe your setup**

preCICE Version: 1965ceb

**Describe the problem**
Using the `linear-cell-interpolation` mapping without providing any connectivity leads to the following warnings/logs

```bash
---[precice] WARNING:  2D Mesh "Solid-Mesh" does not contain triangles. Linear cell interpolation falls back to nearest projection mapping.
---[precice]  All vertices are inside cells, no fallback to Nearest-Projection required
```

This is very confusing and some people might think that the LCI mapping just works (without providing connectivity.

**Step To Reproduce**
1. Select a tutorial case without connectivity (I used the perpendicular-flap)
2. exchange one of the mappings to use linear-cell-interpolation

**Expected behaviour**
A clear warning saying what is actually wrong and what should be changed.

FYI: @boris-martin

**Comment by boris-martin** [comment]
In `LinearCellInterpolation.cpp`:
```
  if (!fallbackStatistics.empty() && !missingConnectivity) {
    PRECICE_INFO(
        "Linear Cell Interpolation is used, but some points from {} don't lie in the domain defined by the {}. "
        "These points have been projected on the domain boundary. This could come from non-matching discrete geometries or erroneous connectivity information."
        "If distances seem too large, please check your mesh. "
        "The projection statistics are: {} ",
        searchSpace->getName(), getDimensions() == 2 ? "triangles" : "tetrahedra",
        fallbackStatistics);
  } else {
    PRECICE_INFO("All vertices are inside cells, no fallback to Nearest-Projection required");
  }
```

I think the "else" should be replaced by `else if (!fallbackStatistics.empty())`.

Alternatively, the whole block should be inside a `if (!missingConnectivity)` and then we check for the fallbackStatistics.

Expected behavior:

- If everything is good, say it
- If fallback occured (but at least one volume element is present), print the fallback statistics
- If no volume element is present, say that NP is used _and don't say that evertyhing is fine afterwards_.

As further improvements, we could also check if surface elements are present: if no connecitivity at all is configured, we say that we fall back to NP, while we actually fall back to NN (actually a NP that itselfs falls back to NN)
