### ISSUE TITLE
Make `dt` argument in read data functions mandatory

### ISSUE THREAD

**Issue by BenjaminRodenberg** [precice/precice#1603]
The technical discussion in #1559 actually brought us to a bigger usability discussion about making the `dt` argument in all read data functions mandatory. This is a big step for our users, because they will always have to provide a `dt`, but this also means they have to realize that read data is always connected to some kind of timing and that there is a waveform behind the scenes.

**Describe the solution you propose.**

Make `dt` mandatory. The default behavior of v2 could still be realized by users easily, if they provide `dt = precice_dt` (where `precice_dt` is obtained from `advance`)

**Describe alternatives you've considered**

In version 2 we provide a default for `dt`. This makes `dt` optional. However, there is a technical problem with the C/Fortran bindings (see #1559)

**Comment by davidscn** [comment]
Discussion in person.

In order to make the users thinking carefully about the time associated to the data, we want to make the `dt` argument mandatory in the 'default' (depending on conclusions in #1559) read data functions.

```cpp
std::size_t readData(string_view meshName, string_view dataName,
    span<const int> vertexIds, double dt, span<double> data) const;
```

Main question is whether we want to provide a function reading _only_ at the end of a given time-window, e.g.,
 
```cpp
std::size_t readDataAtTimeWindowEnd(string_view meshName, string_view dataName,
    span<const int> vertexIds, span<double> data) const;
```

Pro argument:

- there are very simple coupling scenarios, where the time-stepping is irrelevant and the requirement is an overkill
- data is always available at the end of a time-window; we could potentially bypass the waveform sampling when using the second version, which _could_ perform better 

Contra argument:

- this would need to go into all bindings
- one could always use preCICE API functions to get the same functionality (e.g. the current return value of `advance`), however, this might be tedious in very simple cases
- the second version might mitigate the enforcement of the mandatory `dt` in the first place

Conclusion: We don't provide the second version and enforce the `dt` requirement via the first version.

**Comment by BenjaminRodenberg** [comment]
Important side effect of this decision: This basically makes the waveform API and features that are currently declared experimental non-experimental, because forcing every user to use an experimental feature does not make sense. I think that's perfectly fine for v3, but it's something we should keep in mind. (note: We could still declare waveform-order > 0 as experimental, if we want)
