### ISSUE TITLE
Do not interpolate data for existing timestamps

### ISSUE THREAD

**Issue by fsimonis** [precice/precice#1752]
**Please describe the problem you are trying to solve.**

When reading data for a given dt, then `time::storage` creates a b-spline and interpolates based on it.
Only exception is if there is only a single data point.

If a sample already exists at the given dt, then the time storage still interpolates instead of returning the matching sample.

**Describe the solution you propose.**

Directly use a sample if the requested time matches its timestamp.

**Additional context**

https://github.com/precice/precice/pull/1746

**Comment by BenjaminRodenberg** [comment]
In the [documentation](https://www.eigen.tuxfamily.org/dox/unsupported/structEigen_1_1SplineFitting.html#adc80b6f0dd0dbbea28130fb254626874) of Eigen it says

> Fits an interpolating [Spline](https://www.eigen.tuxfamily.org/dox/unsupported/classEigen_1_1Spline.html) to the given data points.

Interpolating spline means it fulfils the interpolation condition, meaning $f(t_i) = x_i$ for the input data points $(t_i,x_i)$. The fitting is here only how this is done algorithmically, because you need to somehow find the control points that fulfill the interpolation condition. I'm not sure about the tolerance, but it should be small enough, if Eigen claims the resulting spline is interpolating.

Under the hood I assume what's happening is similar to scipy, where the documentation is a bit more helpful. See https://docs.scipy.org/doc/scipy/tutorial/interpolate/smoothing_splines.html#tutorial-interpolate-fitpack.

**Comment by fsimonis** [comment]
I ran into cases where for pretty simple tests, I required a higher tolerance than we use by default.

Concrete example of a midpoint in case of linear interpolation:

https://github.com/precice/precice/blob/b4c5df1f2e059906b43c20543f1c96f74d331b13/src/math/tests/BSplineTest.cpp#L66C14

Maybe we should extend the test coverage here to prevent bad surprises.

**Comment by BenjaminRodenberg** [comment]
> Concrete example of a midpoint in case of linear interpolation:

But that's a different issue, because here you are interpolating and you don't use data from an existing timestamp.

The [following](https://github.com/precice/precice/blob/b4c5df1f2e059906b43c20543f1c96f74d331b13/src/math/tests/BSplineTest.cpp#L96) looks more fitting, no? Here it looks like the interpolation condition is only satisfied up to a certain tolerance.

> Maybe we should extend the test coverage here to prevent bad surprises.

But aren't you already testing this here?

https://github.com/precice/precice/blob/b4c5df1f2e059906b43c20543f1c96f74d331b13/src/math/tests/BSplineTest.cpp#L77-L80

If we use the actual data for time `0.0` we should be able to remove the tolerance `1e-13`. This is then different from the behavior of Eigen, but closer to the actual value. But yes: If we use the actual value and not the value from the Eigen interpolation, we get a small jump here.

My proposal: Let's remove this issue from the 3.0.0 milestone and reconsider it when it really turns into a problem. For now, I would use the Eigen implementation and not introduce exceptions for the sake of performance. Then the implementation is consistent. In the future, we could offer our own implementation for piecewise linear interpolation. Here, we get away without any fitting, we can directly use values that are available and plain linear interpolation comes with much less overhead. Offering different interpolation schemes is on the todo list anyways. (but please let's not start this in 3.0.0)

**Comment by NiklasKotarsky** [comment]
> I ran into cases where I required a higher tolerance than we use by default for pretty simple tests.
> 
> Concrete example of a midpoint in case of linear interpolation:
> 
> https://github.com/precice/precice/blob/b4c5df1f2e059906b43c20543f1c96f74d331b13/src/math/tests/BSplineTest.cpp#L66C14
> 
> Maybe we should extend the test coverage here to prevent bad surprises.

I have replaced the decimal numbers with their corresponding fractions and now the tolerance 10^{-13} works everywhere for the Bspline tests.

**Comment by NiklasKotarsky** [comment]
Yes, I changed I added the changes to https://github.com/precice/precice/pull/1765 were I changed https://github.com/NiklasKotarsky/precice/blob/ef2270b3d68f317ecee51194f4d664338b5d6442/src/math/tests/BSplineTest.cpp#L100C1-L101C104 .

**Comment by BenjaminRodenberg** [comment]
@NiklasKotarsky can we close this issue now? #1765 is merged and this should resolve the issue.

**Comment by NiklasKotarsky** [comment]
Technically this is still open, since I removed the feature due to the previous discussion before fixing the tolerances in #1765. I can open a new pull request that adds this feature again, since the problem with the tolerance and jumping interpolants is now resolved.
