### ISSUE TITLE
Remove support for legacy VTK exports

### ISSUE THREAD

**Issue by fsimonis** [precice/precice#1785]
**Please describe the problem you are trying to solve.**
With #1784, we drop the automatic fallback of the legacy VTK exporter to VTU, when used in parallel.

This raises the question if we should remove the legacy VTK exporter altogether.

Is there any use-case for this?

@MakisH @davidscn is the `<export:vtk/>` necessary for the systemtests, the tutorials, or ASTE? 

**Describe the solution you propose.**

If there are no use-cases, remove `<export:vtk/>` altogether.

**Describe alternatives you've considered**

* Keep the vtk exporter for serial participants
* Make `<export:vtk/>` an alias for `<export:vtu/>`. Instead of exporting using the legacy VTK text format, we export unstructured VTK files.

**Additional context**

See #1772

**Comment by MakisH** [comment]
> @MakisH @davidscn is the `<export:vtk/>` necessary for the systemtests, the tutorials, or ASTE?

For the system tests, we use [fieldcompare](https://gitlab.com/dglaeser/fieldcompare) to compare results, which does support modern VTK formats. However, it looks like we currently do export legacy `.vtk` files instead of `.vtu` when running the tests (cc @valentin-seitz).

For the tutorials, I cannot think of any case where the legacy format is needed.

I am fine removing the legacy VTK exporter, if there is a reason to do so. The only potential use case would be to import preCICE exports in solver-specific post-processing tools or in-house post-processing scripts of any researcher. Such a case could be for community simulation tools (e.g., DHCAE Tools, DAPTA, etc), but I have no idea if this is the case.

In any case, I would keep the `export:vtk` as an alias for `export:vtu`. Besides the filename, VTK is the name of the umbrella of formats, it is what people know/remember, and what we already have in our docs, forum posts, etc.

**Comment by davidscn** [comment]
Both, VTK and VTU exports are in use in ASTE. I don't see the reason to remove the VTK exports. It would require compatibility changes in ASTE. Functionality would remain the same.

**Comment by uekerman** [comment]
Then, let's keep the functionality for now.
