### ISSUE TITLE
Buggy "value=-1" input for First-participant timestep configuration

### ISSUE THREAD

**Issue by steffenger** [precice/precice#2011]
If you choose the "first-participant" method for the time-window-size,  you are instructed to enter value=-1 ín your configuration file.

https://github.com/precice/precice/blob/develop/src/cplscheme/config/CouplingSchemeConfiguration.cpp#L224-L229

According to @BenjaminRodenberg this is more for internal handling and therefore a "buggy" input for the user.

**Comment by uekerman** [comment]
Which config runs into this error? We should probably forbid the config in the first place already.

**Comment by steffenger** [comment]
You run into this error if you dont remove the value tag after choosing "first participant".

```bash
<time-window-size value="1" method="first-participant"/>
```

```bash
15:29:48 [cplscheme::CouplingSchemeConfiguration]:215 in xmlTagCallback: ERROR: Time window size value has to be equal to -1 (default), if method="first-participant" is used. Please check the <time-window-size value="1" method="first-participant" /> tag in the <coupling-scheme:...> of your precice-config.xml
```

**Comment by uekerman** [comment]
Yes, we could do better here. Thanks for reporting!

**Comment by BenjaminRodenberg** [comment]
To maybe contribute some internal information here: We use `-1` as a sentinel value for "no time window size defined". Therefore, I guess providing `value="-1"` with `method="first-participant"` is technically valid, but very confusing from the usability side, because this is actually an implementation detail that we expose to the user here. I think raising an error, if any `value` is provided while `method="first-participant"` is set would be the right way to go here.
