### ISSUE TITLE
Replace assertions by checks in Triangle creation

### ISSUE THREAD

**Issue by uekerman** [precice/precice#372]
Currently, several false user inputs are not caught by checks, but only by assertions when creating Triangles. E.g. whether three edges really form a triangle. 

https://github.com/precice/precice/blob/develop/src/mesh/Triangle.cpp#L16-L72

**Comment by fsimonis** [comment]
The big question is where we should check this.

**Check the user input at the interface keeping the library internals sane.**
https://github.com/precice/precice/blob/cfe7e9850b1c5c9fc1bf4ab5cec306ede8ef01b8/src/precice/SolverInterface.cpp#L192-L197

**Let the Mesh check it when requested to create the Triangle.**
https://github.com/precice/precice/blob/cfe7e9850b1c5c9fc1bf4ab5cec306ede8ef01b8/src/mesh/Mesh.cpp#L150-L154

**Throw during the constructor of the Triangle.**
https://github.com/precice/precice/blob/cfe7e9850b1c5c9fc1bf4ab5cec306ede8ef01b8/src/mesh/Triangle.cpp#L16-L20

In order to keep the library clean, I prefer to keep input checking as close to the `SolverInterface` as possible, however, this requires us to extract the edge information from the Mesh first.
The Mesh seems to be the right place for this check as it is already responsible to keep the edges and vertices. Is holds all the necessary information and moving the checks into the Mesh would simplify the `Triangle` class.
