### ISSUE TITLE
Inconsistency in comment and implementation of Propertycontainer::getProperties

### ISSUE THREAD

**Issue by fsimonis** [precice/precice#413]
https://github.com/precice/precice/blob/d7d130fd797c83d4c6c2d877d4d1b08c1d3e9e9e/src/mesh/PropertyContainer.hpp#L113-L115

https://github.com/precice/precice/blob/d7d130fd797c83d4c6c2d877d4d1b08c1d3e9e9e/src/mesh/PropertyContainer.hpp#L151-L166

**Comment by floli** [comment]
I think a more appropriate comment would be 
```
  /**
   * @brief Recursively looks up a property ID.
   *
   * @param[in] propertyID ID to lookup
   * @param[out] properties found
   */
  template <typename value_t>
  void getProperties(int propertyID, std::vector<value_t> &properties);
```
some questions remain:

* Why not use the return value instead of a call-by-reference out argument?
* The implementation looks half-baked. Mental edit: Seems ok, if the ID is unique, which is the case here.

and BIG QUESTION:

* Do we use the `PropertyContainer` at all? Yes, it's *used* in the mesh, but is it actually **used**?

**Comment by uekerman** [comment]
> Do we use the PropertyContainer at all? Yes, it's used in the mesh, but is it actually used?

My best guess would be that this is not used (no longer used since geometries died). But could be interesting for #374 ?
