### ISSUE TITLE
Implement API functions to directly access properties from preCICE config

### ISSUE THREAD

**Issue by BenjaminRueth** [precice/precice#433]
It might be helpful to expose some of the parameters defined in the preCICE config via API calls to the participants. Let's collect candidate + use-cases here. We do not want to expose all properties to the solver, since this unnecessarily blows up the API, which has implications w.r.t testing etc.

Loosely related to #261

**Comment by BenjaminRueth** [comment]
expose

```
    <coupling-scheme:serial-implicit>
        <max-time value="1"/>
```

via API call `getMaxTime()`

**Use-Case:** One of our users wanted to add a progress bar in one of the solvers. This is not possible, if the maximum simulation time is unknown for the solver.

**Comment by MakisH** [comment]
I don't really like the idea of getting things directly from the configuration file: the configuration file is owned by preCICE, and if preCICE wants to set some settings differently (e.g. due to defaults, heuristics, etc), it should be able to do that and the user should not get settings that bypass this mechanism.

I would rather rename and simplidy this issue to "Additional API method getMaxTime", which might also be easier to implement (and easier to evaluate when this issue is "done").

**Comment by MakisH** [comment]
If there are no other use cases, the argument

> We do not want to expose all properties to the solver, since this unnecessarily blows up the API, which has implications w.r.t testing etc.

does not really hold, especially in combination with the dangers described above.

**Comment by MakisH** [comment]
Thinking of it in more detail, a `getMaxTime` method would not be very useful, as in implicit coupling the solver usually needs to rerun the last time window a few times.

In the OpenFOAM adapter we already had this problem, as there we need to overwrite the solver's end time, so that the adapter (function object) keeps getting called in the last time step.

**Comment by BenjaminRueth** [comment]
I think this issue is a duplicate of the closed issue https://github.com/precice/precice/issues/682. As far as I understand, the same argumentation holds here, therefore, we can close this issue. If I'm missing something feel free to reopen it.
