### ISSUE TITLE
Passing of Time Series Data

### ISSUE THREAD

**Issue by huangq1234553** [precice/precice#463]
This issue is to request additional functionality in preCICE. Currently, I am working with a coupling that passes time series data (data passed has 4 dimensions of x1, y1, z1, t1) when coupling between the two solvers occurs. This is because each solver runs for a  set time period (one revolution/period in periodic system) before data is transferred. One solver can only accept time series data when calculating data for the next revolution. This is a problem because preCICE limits the length of the vector passed at each vertex ID to a maximum of 3 values for 3D problems.

There are several ways to solve this problem. One of which is to allow data from multiple timesteps to be connected to a single vertex ID (effectively increasing the vector length of the data associated with each vertex ID). 

Alternatively, one could simulate the timestepping in each revolution by separating the data from each timestep and repeatedly calling the preCICE advance function to pass data multiple times.

I am unsure of the best way to introduce this functionality or deal with this problem. Any suggestions would be appreciated.

**Comment by BenjaminRueth** [comment]
This issue is strongly related to #133

> This is a problem because preCICE limits the length of the vector passed at each vertex ID to a maximum of 3 values for 3D problems.

For your use case, I suggest to not use the functions for reading/writing of vector data, but the functions for scalar data. The vector data functions are to be used for vector valued quantities (velocity, force...), but not for vectors of scalar quantities.

> There are several ways to solve this problem. One of which is to allow data from multiple timesteps to be connected to a single vertex ID (effectively increasing the vector length of the data associated with each vertex ID).

You can use different datasets i.e. `Data1`, `Data2`, ..., `DataN` being connected to the same vertexID. Here is a rough draft that uses the python bindings:

```
for substep in range(1, N+1):
        write_data_name = "Data" + str(substep)
        write_data_id = self.get_data_id(write_data_name, self._mesh_id)
        substep_time = compute_associated_time(substep)
        write_data = get_data(substep_time)
        write_block_scalar_data(write_data_id, n_vertices, vertex_ids, write_data)
```

For more details see [this branch](https://github.com/precice/fenics-adapter/tree/CoupledProblems2019), [this PR](https://github.com/precice/fenics-adapter/pull/35) and [this presentation, slide 5-7](https://mediatum.ub.tum.de/1503903).

> Alternatively, one could simulate the timestepping in each revolution by separating the data from each timestep and repeatedly calling the preCICE advance function to pass data multiple times.

The ideal solution from my perspective is, if the solver with the small time steps (high-rate) calls advance multiple times while the solution with the small time steps (low-rate) calls advance only once within one synchronization window. From the solver's perspective it is beneficial that `precice.advance()` is being called after every timestep, because this means you can develop code that is close to the [adapter example](https://github.com/precice/precice/wiki/Adapter-Example) without the need of introducing additional steps. Ideally, Participant A should not even know that participant B is operating at a different rate. 

## Subcycling

"Vanilla" preCICE already provides subcycling for this purpose (see also this [wiki entry on Adapter's time step sizes](https://github.com/precice/precice/wiki/Adapter's-Time-Step-Sizes)). This is also the reason why `advance` requires you to provide the actual timestep length and returns the maximum allowed timestep size. However, here you usually do not vary the exchanged data over time.

## Waveform relaxation

I already tried to implement something close to what you are looking for by wrapping the preCICE API. Here, the "real" preCICE advance is indeed only called once per window. If you take a look at [this code](https://github.com/precice/fenics-adapter/blob/0a16b9918395cb887b2961fa24ffefbba6420bd5/fenicsadapter/waveform_bindings.py#L125-L179) you can see that [`precice.advance()`](https://github.com/precice/fenics-adapter/blob/0a16b9918395cb887b2961fa24ffefbba6420bd5/fenicsadapter/waveform_bindings.py#L138) is only called if [`window_is_completed()`](https://github.com/precice/fenics-adapter/blob/0a16b9918395cb887b2961fa24ffefbba6420bd5/fenicsadapter/waveform_bindings.py#L128). Otherwise advance is just used to tell the solver the [`remaining_window_time()`](https://github.com/precice/fenics-adapter/blob/0a16b9918395cb887b2961fa24ffefbba6420bd5/fenicsadapter/waveform_bindings.py#L176) (this is similar to what subcycling is doing in "vanilla" preCICE). In this approach the exchanged data does not remain constant inside one window.

**Comment by uekerman** [comment]
To summarize, I see different options:
* Use subcycling: Already fully supported by preCICE but reduces your temporal discretization order.
* Explicitly define `Data1`, `Data2` in your config. This requires that the number of substeps is known (to both solvers) a-priori and is constant. 
 * Try the WR bindings from @BenjaminRueth. Only works if your code is in Python. In the long run (maybe end of the year or spring 2020), we will have a similar feature directly in preCICE. 

Let's discuss the best solution for your problem in person next week!

**Comment by uekerman** [comment]
We decided to go for the second option. In the long run, the waveform relaxation in preCICE will be a proper solution. Closing the issue.
