### ISSUE TITLE
Add access to MeshRequirement to SolverInterface

### ISSUE THREAD

**Issue by fsimonis** [precice/precice#467]
## Problem
 
preCICE does not always require connectivity information for meshes.
In case a configuration uses only nearest-neighbor/RBF mappings for a given mesh, then it does not require connectivity information and will ignore calls to `setMeshEdge` and `setMeshTriangle`.
This reduces bookkeeping and memory consumption inside the preCICE library.

The adapter using preCICE does not know about this information and always has to generate the connectivity information and call `setMeshXXX`.

## Proposition

We should consider adding a function to the interface that allows to fetch this information.

This allows the adapter to conditionally skip the unnecessary generation of this information.

Example:
* `bool getMeshRequireEdges(int meshID) const`
* `bool getMeshRequireTriangles(int meshID) const`

**Comment by uekerman** [comment]
Why does the old solution generate bookkeeping and memory consumption. Isn't all of that only shifted to the adapter then? 
The only advantage I see of this solution is to reduce memory consumption in the adapter. Downside is that it becomes more complicated for the user.

**Comment by fsimonis** [comment]
> Why does the old solution generate bookkeeping and memory consumption. Isn't all of that only shifted to the adapter then?

Not sure what you mean. The adapter always has to generate the connectivity information unless it is switched off at compile time. There is no way for the adapter to check this at runtime.

> The only advantage I see of this solution is to reduce memory consumption in the adapter. Downside is that it becomes more complicated for the user.

Exactly! This is very similar to [`isWriteDataRequired`](http://xgm.de/precice/docs/develop/classprecice_1_1SolverInterface.html#a45e7a0a93a087819a1877449ce86b010) . A user can check this in the adapter to reduce unnecessary work, but does not have to.

**Comment by uekerman** [comment]
Would the OpenFOAM and the CalculiX adapter benefit from this?

**Comment by MakisH** [comment]
> > Why does the old solution generate bookkeeping and memory consumption. Isn't all of that only shifted to the adapter then?
> 
> Not sure what you mean. The adapter always has to generate the connectivity information unless it is switched off at compile time. There is no way for the adapter to check this at runtime.

Which adapter do you have in mind here?

In the OpenFOAM adapter we have configure this at runtime using [`provideMeshConnectivity: true`](https://github.com/precice/openfoam-adapter/tree/master/tutorials/CHT/flow-over-plate/buoyantPimpleFoam-laplacianFoam_nearest-projection). Of course, this is an additional thing that the user needs to understand and configure and automation would be welcome.

This actually raises the question of why we need adapter configuration files instead of reading (almost) everything from the main preCICE configuration file and making it available to each adapter. Maybe apart from the participant name, patch names, and special features, the `write-data`, `read-data`, `mesh` and connectivity requirements could be inquired directly from preCICE.

I actually like this idea also for consistency with the high-level API idea. For example, the user does not need to configure an adapter to keep checkpoints when asking for implicit coupling. It's rather the adapter that asks preCICE if this is needed. Why not do the same here?

**Comment by fsimonis** [comment]
@IshaanDesai and I came up with clearer names:

```cpp
bool SolverInterface::areMeshEdgesRequired(int meshID) const;
bool SolverInterface::areMeshTrianglesRequired(int meshID) const;
```

**Comment by IshaanDesai** [comment]
Adding API functions to access requirement of mesh connectivity information would optimize adapter initialization and the FEniCS adapter is a strong case for this. In the adapter initlialization, mesh connectivity information [is generated](https://github.com/precice/fenics-adapter/blob/69a16bdf9d237e512e2e1ae9ef4ed1bb983ea5b9/fenicsprecice/fenicsprecice.py#L412-L418) irrespective of the mapping configuration. 
The function [get_coupling_boundary_edges](https://github.com/precice/fenics-adapter/blob/69a16bdf9d237e512e2e1ae9ef4ed1bb983ea5b9/fenicsprecice/adapter_core.py#L366) is not cheap and for bigger cases with nearest neighbor mapping or RBF mapping this function this call can be avoided altogether.
Having these functions also aligns with the high-level API philosophy.

**Comment by uekerman** [comment]
I agree on the rationale to add sth.

Is there an argument against only having one function?

```c++
bool SolverInterface::isMeshConnectivityRequired(in meshID) const;
```

**Comment by fsimonis** [comment]
@uekerman The reason for separate functions is the projection to volumes #468.
This leads to cases where only some connectivity is required.

2D Nearest Projection | Edges Required? | Triangles Required?
--- | --- | ---
to interfaces | :heavy_check_mark: | :x: 
to "volumes" | :heavy_check_mark: | :heavy_check_mark:

**Comment by uekerman** [comment]
But the adapter would know best whether a mesh is a volume or a surface mesh. Currently, preCICE does not know this at all.
If we go to 3D, the number of API function we'll need would go up further.

**Comment by fsimonis** [comment]
> Currently, preCICE does not know this at all.

preCICE will need to know this to realise projection to volumes #468 and currently supports only projections to interfaces.

> If we go to 3D, the number of API function we'll need would go up further.

True, there would at least be an `areMeshTetrahedraRequired()`.

> But the adapter would know best whether a mesh is a volume or a surface mesh. 

So, what you mean is that the adapter would provide the correct connectivity anyhow.
The adapter only needs to know weather connectivity is required or not. Correct?

**Comment by uekerman** [comment]
> preCICE will need to know this to realise projection to volumes #468 and currently supports only projections to interfaces.

Yes, absolutely. For me it is still an open questions whether we want to put that into the preCICE configuration or let the adapter tell preCICE. But such a discussion is beyond this issue. In any case, the adapter always knows whether a mesh is a volume or a surface mesh.

> So, what you mean is that the adapter would provide the correct connectivity anyhow.
The adapter only needs to know whether connectivity is required or not. Correct?

Exactly. That's why one function could/should be enough.
