### ISSUE TITLE
JSON as alternative to XML for the configuration

### ISSUE THREAD

**Issue by j8asic** [precice/precice#529]
I've noticed that `nlohmann/json.hpp` is already used in the build (for events reporting?). Can it be used for the configuration instead of XML?

**Comment by uekerman** [comment]
Yes, we use json for our profiling. Of course, json could be used instead of xml for configuration. It would be some effort though and, more important, destroy backward compatibility (if we do not maintain both). Is there any strong argument to use json over xml? 
Maybe more interesting could be a converter. We already working on a [config generator](https://github.com/precice/controller) though not very actively at the moment.

**Comment by j8asic** [comment]
I see... I would not ask for code restructuring, only adding another option on transferring the info, if and only if preCICE XML stuff is detached from the preCICE core and just passes on the parsed data. No argument against XML, except for preference and wanting to remove XML dependency.

**Comment by uekerman** [comment]
It is detached from the preCICE core, but adding JSON as another option would mean to maintain both. The XML stuff happens [here](https://github.com/precice/precice/tree/develop/src/xml). I see your dependency argument. The XML dependency is, however, not the one hurting us much at the moment. 

I am closing this for the moment as I don't see a high enough cost / benefit ratio. If anyone wants to continue in this direction or sees other arguments, please reopen.
