### ISSUE TITLE
Remove `MeshHandle` and replace with easier solution for white-box testing

### ISSUE THREAD

**Issue by uekerman** [precice/precice#588]
`MeshHandle` opens our API to read coordinates and values of a received mesh (but not to modify them, which would lead to severe problems). To my best knowledge, historically, this had two use cases:
* (A) In an immersed boundary approach, to update the coordinates of the local Eulerian mesh, we need the values of the received Lagrangian mesh.
* (B) We don't want to define a local mesh, but just use the received mesh.

(A) is no longer supported as we currently don't support dynamically changing meshes. This might [get interesting again](https://github.com/precice/precice/projects/2).
(B) is currently only possible for a serial participant (but not documented). A parallel participant would need a re-partitioning, which is not possible without local information. (Or some alternative like holding a copy of the entire mesh in every rank). 

Furthermore, we still use `MeshHandle` in integration tests.

* as some sort of helper functionality, which could easily be replaced
  * [`testEpxlicitWithBlockDataExchange`](https://github.com/precice/precice/blob/develop/src/precice/tests/SerialTests.cpp#L348)
  * [`testExplicitWithDataExchange`](https://github.com/precice/precice/blob/develop/src/precice/tests/SerialTests.cpp#L185)
* to (implicitly) test (B), but could be replaced again 
  * [`testExplicitWithDataScaling`](https://github.com/precice/precice/blob/develop/src/precice/tests/SerialTests.cpp#L660)
* for white-box testing in [`ParallelTests`](https://github.com/precice/precice/blob/develop/src/precice/tests/ParallelTests.cpp), checking number of triangles after re-partitioning etc.

**Conclusion**
* For white-box testing, the concept is over-engineered in my opinion. Still, it would be good to have some entry point here.
* We should remove use case (B) as it does not easily generalize to a parallel participant and is currently not documented.
* There are still many steps to do before (A) could get interesting again. Also, we have already removed all integration tests for (A) some time ago.

My tendency would be to remove it. @fsimonis How do you see these points?

_Originally posted by @uekerman in https://github.com/precice/precice/pull/581#issuecomment-560326848_

**Comment by fsimonis** [comment]
Problems with the MeshHandle:
* It is a proxy type for a `mesh::Mesh`, providing proxy types for `vertices`, `edges` etc. allowing ranged access to the `mesh::Mesh::VertexContainer` etc.  
  This is complex in itself, but becomes even more complex as we have to prevent public dependencies. Thus we cannot simply use a boost iterator helper to simplify a sane iterator implementation.
* The interface is inconsistent with setting mesh information:
  `setMeshVertices(...)` vs `for (const auto& v : getMeshHandle(...).vertices())`

I propose to break the backwards-compatibility for 2.0 by removing the MeshHandle.

We should then add API calls to the `SolverInterface` which are consistent with the `setMeshX` calls.
Important here is that we already have some similar calls:

* [`getMeshVertexIDsFromPositions()`](https://xgm.de/precice/docs/develop/classprecice_1_1SolverInterface.html#ad1271dbe275ca3be8a5b549243919d54)
* [ `getMeshVertexSize()`](https://xgm.de/precice/docs/develop/classprecice_1_1SolverInterface.html#aa47501924a57a314de5d8052448e7cd9)
* [`getMeshVertices()`](https://xgm.de/precice/docs/develop/classprecice_1_1SolverInterface.html#a22c272bbc75b3123c3d2ee38a79bdffa)

Adding a consistent set of API calls will be tricky though, as we currently access vertex positions via ids.
This is not a problem for edges, as they already have ids, but for Triangles and Quads.

Additional Questions:
* Should `getMeshEdges` return vertex coordinates or vertex ids?
* Should `getMeshTriangles` return vertex coordinates, vertex ids, or edge ids?
* Do we have to **break the API** in order to add Triangle and Quad ids?

Table of Interface Functions:

Mesh Primitive `X` | `Vertex` | `Edge` | `Triangle` | `Quad`
--- | --- | --- | --- | ---
`setMeshX` | ✔️ | ✔️  | ✔️ | ✔️
`setMeshXs` | ✔️ | ❌  | ❌ | ❌ 
`setMeshXwithEdges` |  |   | ✔️  | ✔️ 
`getMeshX` | ❌ | ❌  | ❌ | ❌
`getMeshXs` | ❌ | ❌  | ❌ | ❌ 
`getMeshXsFromPosition` | ✔️ |   |  | |
`getMeshXIds` | ✔️ | ❌  | ❌ | ❌ 
`getMeshXSize` | ✔️  | ❌  | ❌ | ❌

**Comment by uekerman** [comment]
I agree with removing `MeshHandle`, but what is the reasoning to replace it? I would just vote to remove the functionality. As explained above (A) and (B) are deprecated and for the white-box testing, we don't need API functions.

**Comment by fsimonis** [comment]
@uekerman My comment https://github.com/precice/precice/issues/588#issuecomment-561141669 is a bump of thoughts for the sake of knowledge preservation.  
This is the essence of the answer:

> I propose to break the backwards-compatibility for 2.0 by removing the MeshHandle.

---

If we add `const Mesh& mesh(std::string name) const` to `SolverinterfaceImpl`, then we can access the mesh from every test using `testing::WhiteboxAccessor::impl()`.

https://github.com/precice/precice/blob/0fd27c29493ed0d1378fb206a77526a91132dd68/src/precice/tests/SerialTests.cpp#L452-L455

Would become:
```cpp
    const auto& vertices = impl(cplInterface).mesh("Test-Square").vertices();
    // SolverTwo does not start the coupled simulation and has, hence,
    // already received the first data to be validated.
    for ( const auto& vertex : vertices ){
```

**Comment by uekerman** [comment]
Yes, I like this solution.
