### ISSUE TITLE
Failing integration tests using PETSc

### ISSUE THREAD

**Issue by uekerman** [precice/precice#591]
On my system currently `PreciceTests/Parallel/GlobalRBFPartitioning` and
`PreciceTests/Parallel/LocalRBFPartitioning` fail (when I only run these specific tests, so no clean-up problem). 

Ubuntu 18.04, PETSc 3.7

I could boil it down to a single change.
* Fails already for: https://github.com/precice/precice/commit/e0923fdeedc5fc63aad80ea2c09b3efa3ac62e6f
* Still works with: https://github.com/precice/precice/commit/b9ff8bcd3f21e24b5e121f2410bcb7d5ee392885

So, the problem must be here, I am puzzled however where exactly:
https://github.com/precice/precice/compare/b9ff8bcd3f21e24b5e121f2410bcb7d5ee392885...e0923fdeedc5fc63aad80ea2c09b3efa3ac62e6f

**Comment by uekerman** [comment]
Error btw is
```
[0]PETSC ERROR: VecScatterCreate_PtoP() line 2896 in /build/petsc-vurd6G/petsc-3.7.7+dfsg1/src/vec/vec/utils/vpscat.c
[0]PETSC ERROR: Out of memory. This could be due to allocating
[0]PETSC ERROR: too large an object or bleeding by not properly
[0]PETSC ERROR: destroying unneeded objects.
```

**Comment by fsimonis** [comment]
I cannot reproduce this with PETSc version 3.10.

**Comment by fsimonis** [comment]
@uekerman I was able to reproduce the bug inside an Ubuntu 18:04 LTS docker container after installing the dependencies.

When running `PreciceTests/Parallel/GlobalRBFPartitioning` the master rank 0 crashes with the following message:
```
[0]PETSC ERROR: VecScatterCreate_PtoP() line 2896 in /build/petsc-vurd6G/petsc-3.7.7+dfsg1/src/vec/vec/utils/vpscat.c
[0]PETSC ERROR: Out of memory. This could be due to allocating
[0]PETSC ERROR: too large an object or bleeding by not properly
[0]PETSC ERROR: destroying unneeded objects.
[0]PETSC ERROR: Memory allocated 0 Memory used by process 52604928
[0]PETSC ERROR: Try running with -malloc_dump or -malloc_log for info.
```
The other ranks get terminated due to rank 0 aborting.

The last log message from SolverOne Ranks `0,1,2` suggest that they crash at the same collective operation after the following lines:
https://github.com/precice/precice/blob/b20780810baf4d36ed6bcd5715a27518643596e0/src/mapping/PetRadialBasisFctMapping.hpp#L429-L430
and before the lines:
https://github.com/precice/precice/blob/b20780810baf4d36ed6bcd5715a27518643596e0/src/mapping/PetRadialBasisFctMapping.hpp#L460-L462

Given the crash occurs in a collective of the master Rank of SolverOne and that it has to do with allocation, I suspect that the crash results from these lines:
https://github.com/precice/precice/blob/b20780810baf4d36ed6bcd5715a27518643596e0/src/mapping/PetRadialBasisFctMapping.hpp#L433-L436

The called allocate function is defined here:
https://github.com/precice/precice/blob/b20780810baf4d36ed6bcd5715a27518643596e0/src/utils/Petsc.cpp#L203-L221

**Comment by uekerman** [comment]
Some notes. Overall, I am still puzzled:

* Sometimes the error message reads
```
[0]PETSC ERROR: VecScatterCreate_PtoP() line 2937 in /build/petsc-vurd6G/petsc-3.7.7+dfsg1/src/vec/vec/utils/vpscat.c
    Total message lengths 1 not as expected -2024519024
```
* My gut feeling tells me that this has sth to do with the restricted MPI communicator we use here:

https://github.com/precice/precice/blob/3f279a04dffac8a98ed68848046e413b988311a1/src/precice/tests/ParallelTests.cpp#L156-L163

* Apparently the system PETSc of Ubuntu 18.04 has issues with the system MPI, see e.g. [here](https://github.com/underworldcode/underworld2/issues/288#issuecomment-422264187)

* Sth that looks fishy is that we initialize `PETSC_COMM_WORLD` to a wrong communicator for integration tests (but I don't see how this is related to the commits above)

https://github.com/precice/precice/blob/36ebf6983cfba568d9f59308770c732eba724f49/src/utils/Petsc.cpp#L56-L73 

* Could it also be related to #115?

**Comment by fsimonis** [comment]
The error looks very similar to the one in #526

**Comment by uekerman** [comment]
Our current hope is that refactoring the initialization and finalization of our tests (@fsimonis looks into this) could solve this.

**Comment by fsimonis** [comment]
The test redesign is out of scope for the release 2.0

**Comment by fsimonis** [comment]
@uekerman Did the test redesign in #702 change the situation?

**Comment by uekerman** [comment]
Tests work with PETSc 3.12, but still crash for PETSc 3.7, but probably due to #115.

**Comment by uekerman** [comment]
@fsimonis and me decided to increase the required PETSc version to 3.12 as we are still puzzled why 3.6-3.11 does not work despite all lot of testing.
