### ISSUE TITLE
Rename value_indices and value_index to vertex_ids and vertex_id

### ISSUE THREAD

**Issue by BenjaminRodenberg** [precice/precice#670]
https://github.com/precice/precice/blob/56832a9fe7ac2a06c756b78a3c2cf0e0a96c3dac/src/precice/SolverInterface.hpp#L650

**Comment by BenjaminRueth** [comment]
Is this change actually something everybody agrees on? It will have an effect on the name used in `SolverInterface.hpp`. This means that it is non breaking, but still visible to the user.

Since the original description of this issue lacks some context: I think it makes sense to do this renaming, since [one usually uses the IDs provided by `setMeshVertex/setMeshVertices`](https://github.com/precice/precice/blob/b78686a958f390041b876cc3cf140274f47b0e8b/examples/solverdummies/cpp/solverdummy.cpp#L63). Calling these IDs for vertices `valueIndices` in `SolverInterface.hpp` is not consistent. 

Note: Our solverdummies actually already [use the name `vertexIDs`](https://github.com/precice/precice/blob/b78686a958f390041b876cc3cf140274f47b0e8b/examples/solverdummies/cpp/solverdummy.cpp#L83).

**Comment by uekerman** [comment]
Good point. If we touch this we should have a thorough look, I guess there are more such things.
I still find it a bit weird though to do this in a minor release. Could anything go wrong here?

**Comment by fsimonis** [comment]
This would be resolved via #1559

**Comment by BenjaminRodenberg** [comment]
Closing this issue. #1577 was merged.
