### ISSUE TITLE
Generate a libprecice.pc for the binary tree

### ISSUE THREAD

**Issue by fsimonis** [precice/precice#674]
# Problem Description

We currently only generate a `libprecice.pc` file usable after installing preCICE.
This requires users to install preCICE in order to use it in `pkg-config`-based adapters etc.
It would be nice to provide an additional pkg-config to use preCICE from the binary directory.

# Potential Solution

Generate a pkg-config usable from the binary dir.

**Comment by ajaust** [comment]
I just saw this change in the change logs. It am curious how this change makes **adapter** development easier. I rather see some risks that the "installation process" of keeping everything in the `build` directory is different from the "real" installation process where the library etc. is installed to the `prefix`.

Just from my experience/adapter development process:
When I develop an adapter, I change code outside of preCICE. This means I only need to build preCICE as `debug` build once and put it in a safe location. Afterwards I develop the adapter. If I develop another adapter, I can reuse this existing installation of a preCICE `debug` build. I simply have a `release` and a `debug` build that I switch in between easily and that I only have to set once when a new preCICE version is released.

I rather see some benefit from this change for developing preCICE since I do not have to run the `make install` step the whole time. This makes is easier/fast for me to test changes made to preCICE by rebuilding preCICE more often.

**Comment by fsimonis** [comment]
@ajaust This applies to adapters relying on pkg-config to locate preCICE.

If you wanted to develop your adapter using a custom build of preCICE up to now, you had two options:
* either you needed to compile and install preCICE in some directory. Then use PKG_CONFIG_PATH to make that installation discoverable, or
* change the adapter Makefile (or similar) replacing pkg-config by some other method like setting CPATH and the like.

The problem arises when your preCICE build needs to change during development.
This can be a new version of preCICE itself, or you need to change the build type.
Then this requires reinstalling various builds into the same location, which can be a tedious process.

This change allows you to directly point PKG_CONFIG_PATH directly to the build directory of preCICE. Switching between versions and build type (debug, release, and release with debug log)  is now super easy.

> I rather see some benefit from this change for developing preCICE since I do not have to run the make install step the whole time. This makes is easier/fast for me to test changes made to preCICE by rebuilding preCICE more often.

That's a big benefit too, but not the primary motivation for the change. I think @MakisH was the first to request this for simplifying the work on the OpenFOAM adapter.

**Comment by ajaust** [comment]
I understand and see the benefit if it is about custom builds of preCICE or when uses an often changing development branch of preCICE one has to rebuilt often. If it is only about switching between a release and a debug build, I think there would be cleaner approaches to switch between these versions (e.g., [lmod](https://lmod.readthedocs.io/en/latest/) or simply resetting environment variables).

**Comment by MakisH** [comment]
@ajaust still, in my experience, for many users it is more natural to just build in a local directory and not install. This is most common, e.g., when people just want to try preCICE for some time and then delete it. So, this is also a nice user-facing feature. :-)
