### ISSUE TITLE
The debian package contains unnecessary dev dependencies

### ISSUE THREAD

**Issue by fsimonis** [precice/precice#678]
# Problem Description

The debian package contains building dependencies, which are not required by the user.
We should reduce the required dependencies to the actual runtime dependencies.

**Comment by fsimonis** [comment]
We should remove all internal dependencies an replace `-dev` dependencies with their actual ones.
https://github.com/precice/precice/blob/3204f47af46a53750d3840ef14fc9fd65d7fc3ba/cmake/CPackConfig.cmake#L64

**Comment by MakisH** [comment]
I understand that we need:
- [`libc6`](https://packages.ubuntu.com/focal/libc6) is fine
- Probably we don't need `libboost-dev`, I could not find any equivalent
- [`libboost-log1.71.0`](https://packages.ubuntu.com/focal/libboost-log1.71.0) :warning: **version-named** - there is no virtual `libboost-log` :warning:  (1.71.0 for Ubuntu 20.04, 1.67.0 for Ubuntu 19.10, 1.65.1 for Ubuntu 18.04), instead of `libboost-log-dev`.
- [`libboost-thread1.71.0`](https://packages.ubuntu.com/focal/libboost-thread1.71.0)
- [`libboost-filesystem1.71.0`](https://packages.ubuntu.com/focal/libboost-filesystem1.71.0)
- [`libboost-program-options1.71.0`](https://packages.ubuntu.com/focal/libboost-program-options1.71.0)
- [`libboost-test-1.71.0`](https://packages.ubuntu.com/focal/libboost-test1.71.0)
- [`libxml2`](https://packages.ubuntu.com/focal/libxml2) instead of `libxml2-dev`
- No Eigen (header-only, there is no package anyway)

I am not sure if we need all of these, though

**Comment by fsimonis** [comment]
IMHO the hassle of having to generate the correct versions of boost for the correct versions of ubuntu etc is surpassing the benefits of the reduced disk space.
