### ISSUE TITLE
Add getter functions for time

### ISSUE THREAD

**Issue by BenjaminRueth** [precice/precice#682]
preCICE only offers few API functions to give the user information about the actual time (even though the command line output does to some degree). I think adding some more getter functions will help us and users to have a better overview over the actual state (with respect to point time) of the simulation, since the situation becomes more complex, if subcycling is used. If the solver or adapter has to keep track of time, it currently has to do this independently of preCICE, even though preCICE has information about its state in time (refer to the [fenics-adapter](https://github.com/precice/fenics-adapter/blob/305fd066f35eb48ae360fbdd474aef1b57ac37eb/fenicsadapter/fenicsadapter.py#L648), where time is tracked and updated as one of the state variables of the adapter)

This feature is related to #133.

# Current state

Currently the following functions are related to time stepping:

[`double initialize()`](https://github.com/precice/precice/blob/56832a9fe7ac2a06c756b78a3c2cf0e0a96c3dac/src/precice/SolverInterface.hpp#L94) returns the `time-window-size` specified in `precice-config.xml`. This tells the solver how large its maximal timestep size is.

[`double advance(dt)`](https://github.com/precice/precice/blob/56832a9fe7ac2a06c756b78a3c2cf0e0a96c3dac/src/precice/SolverInterface.hpp#L143) returns the time that is left in the current window after a timestep of size `dt` (and possibly previous timesteps) has been completed.

[`bool isTimeWindowComplete()`](https://github.com/precice/precice/blob/56832a9fe7ac2a06c756b78a3c2cf0e0a96c3dac/src/precice/SolverInterface.hpp#L243) returns `true`, if the end of a coupling window is reached **and** the coupling is successful.

# Proposed methods

`double getTimeWindowSize()`

`double getTime()`, time is updated **after** `advance(dt)` has been called.

`double getTimeWindowStart()`

`double getTimeWindowEnd()` (redundant to `getTimeWindowStart() + getTimeWindowSize()`)

I hope that the methods are mostly self-explanatory. If not, we will probably have to improve the naming.

# Example

Here is a short usage example in python-inspired pseudocode to illustrate the desired behaviour of the methods

```python

solver_dt = 0.1
precice_dt = precice.initialize()  # time-window-size = 0.5

# while(precice.isCouplingOngoing()) loop is unrolled for better readability

# compute first window

assert(precice.getTime() == precice.getTimeWindowStart())  # 0.0
assert(precice.getTimeWindowSize() == precice_dt)  # 0.5

dt = min([precice_dt, solver_dt])  # 0.1
solve(dt)
print(precice.getTime())  # 0.0
precice_dt = precice.advance(dt)  # 0.4
print(precice.getTime())  # 0.1
dt = min([precice_dt, solver_dt])  # 0.1

# proceed until window end
solve(dt)
precice_dt = precice.advance(dt)  # 0.3
print(precice.getTime())  # 0.2
dt = min([precice_dt, solver_dt])  # 0.1

solve(dt)
precice_dt = precice.advance(dt)  # 0.2
print(precice.getTime())  # 0.3
dt = min([precice_dt, solver_dt])  # 0.1

solve(dt)
precice_dt = precice.advance(dt)  # 0.1
print(precice.getTime())  # 0.4
dt = min([precice_dt, solver_dt])  # 0.1

solve(dt)
precice_dt = precice.advance(dt)  # 0.5; assuming that we need one more coupling iteration
assert(not precice.isTimeWindowComplete())
print(precice.getTime())  # 0.0
assert(precice.getTime() == precice.getTimeWindowStart())  # 0.0
assert(precice.getTimeWindowSize() == precice_dt)  # 0.5

# do 4 * solve(dt) and 4 * precice.advance(dt)

print(precice.getTime())  # 0.4
dt = min([precice_dt, solver_dt])  # 0.1
solve(dt)
precice_dt = precice.advance(dt)  # 0.5; coupling is successful
assert(precice.isTimeWindowComplete())
print(precice.getTime())  # 0.5
assert(precice.getTime() == precice.getTimeWindowStart())  # 0.0

...
```

**Comment by fsimonis** [comment]
Is this visualisation correct?

![time-stepping](https://user-images.githubusercontent.com/13552216/75165507-ca22bc00-5722-11ea-84b2-7ab387e82dd5.png)

**Comment by uekerman** [comment]
Already discussed personally with @BenjaminRueth: I don't see a use case for these methods. They kind of contradict a design decision of preCICE to let the solvers not worry about time. For most cases, it's not necessary that a solver knows where it is during a time window. The only exception could be synchronized visualization (both solvers should write output at the same time), which can be covered through `isTimeWindowComplete`.

If the only use case is debugging, improving debugging output should be the better option. But the main info output per advance actually prints all this information already.

I believe that @BenjaminRueth viewpoint comes from the fact that he so far has mainly developed solvers (from scratch) specifically for coupling. That's not the case for our users though. They have a complete (legacy) solver that they want to couple. This solver already knows how to treat time. And preCICE being minimally invasive should not interfere much with the solver's time loop. That's why we have functions like
* read/write-checkpoint-required
* is-ongoing

and not functions like:
* is-coupling-converged
* get-iteration-counter
* get-timestep
* ...

@fsimonis A similar picture is [in the wiki](https://github.com/precice/precice/wiki/Adapter's-Time-Step-Sizes). Looks correct expect the input argument of advance which should be `delta t_i`.  

Closing the issue. Sorry for the harsh move. Feel free to re-open if you come up with a use case :smirk: . Maybe I am overseeing something.
