### ISSUE TITLE
Make time measurements configurable

### ISSUE THREAD

**Issue by uekerman** [precice/precice#69]
The user should be able so switch the event time measurement on and off in the config (work package A). Then, we can put more events in as the default case would of course be "switched off".
Concerning the synchronization between ranks of one participant, at the moment, we have the option to sync at the start and the end of an event. Not using this synchronization makes no real sense as we then would only measure the time of the master rank (and we don't know if the master is at a coupling interface or not). Optionally, it would also be convenient to get the timings of each single rank and choose between both options in the config. (work package B) 
 
Furthermore, the synchronization between participants should also be configurable. (work package C).

The plan was that Florian works on A and I, afterwards, add C. What about B? How much effort would that be?

**Comment by floli** [comment]
I think that these features, including design of configuration directives still require some elaboration.

Currently, an Event can have a barrier. If the programmer decides to activate the barrier, it is unconditionally triggered at start (usually at construction of Event object) and stop (usually at destruction).

**Question A:** Should the barrier always be triggered if a synchronization flag from the config is set or only if the flag is set AND the programmer activated the barrier?

**Question B:** Should the programmer have the possibility to overwrite the config sync flag? That will require a tri-state flag (on, off, config), such as a custom enum or bool.Tribool <http://www.boost.org/doc/libs/1_64_0/doc/html/tribool.html>

First draft for XML configuration:
```
<precice-configuration>
  <timings sync="on | off" print="all | master | n € N"
  <solver-interface dimensions="2">
    [...]
  </solver-interface>

</precice-configuration>
```
Right now, we do measurement of every rank, but print only the ones from master.

The combination of ```sync=on``` and ```print=all``` does not make sense, of couse, since the timings are identical.

If ```print=all``` is set, all ranks print. This of course will result in heavily intermingled output, but it's up to the user to provide options to mpirun in order to direct stdout to appropriate files for each rank. preCICE will have to make sure, that the ```EventTimes.log``` files are suffixed by the rank number.

**Comment by scheufks** [comment]
I just want to add some remarks to bear in mind when discussing the events.
 From my perspective, the barrier within the events should be used 
rarely or not at all. When working with a different code we encountered 
major problems using barriers on a large number of processes (i.e., #p > 
16k), resulting in a breakdown of the scalability (time to solution 
actually doubled using twice as many procs as before). Removing the 
barriers solved the problem. There are a number of possible reasons for 
that (MPI switching communication protocol, etc..) however, using a lot 
of barriers is not recommended at all.

I would suggest a solution like this:
Accumulate the timings for every event (on every rank) and performing 
one reduce operation to get the maximum just before shut-down of the 
application (i.e., in EventTimings::finalize()). This yields the longest 
path, which is also what we are interested in when doing time 
measurement. From my perspective, using barriers in the events would not 
only lead to break down of the performance using a high number of ranks, 
but also the timing results are questionable. Using no synchronization 
at all and reporting timings for a specific rank is also useless, as we 
have no idea if the rank lives on the interface, number of unknowns etc.

**Comment by uekerman** [comment]
I would propose the following options (to choose in the configuration):
 (1) No events at all
 (2) Each rank measures on his own, only output in EventTimes.log 
 (3) Barriers, output (only the master) in EventTimes.log + maybe also on shell 
 (4) Barriers + inter-solver sync,  output (only the master) in EventTimes.log + maybe also on shell

Then, each option has it's use case:
(1) The default option, what every normal user would use
(2) Something, HPC users might want to know for load-balancing 
(3) and (4) If we want to run to understand how long each part in preCICE needs. 

Am I missing any case?
If (2) is too complicated to get nice output, we could also leave it aside for the moment

@scheufks 
You reduction version does unfortunately not solve our issues. We would not be able to distinguish between the timing of the solver and the timing of preCICE. The maximum could just be a load-balancing issue of the solver. Thanks for pointing out the issue on very large runs. At the moment, I see no real solution for that at all. Let's keep that in mind.  

The xml above is good. I would simply use the four proposed options (good names for the options are still an open problem) and put case (1) as default if "timings" is not provided. 

I would close the choice of the event barrier for the developer and leave it completely up to the user. We then could get a problem if a certain event is not triggered by all procs (but e.g. only those at the interface). Do we have/need such cases?
