### ISSUE TITLE
Refactor type alias Bounding Box into class 

### ISSUE THREAD

**Issue by uekerman** [precice/precice#705]
What once started as a small addition

https://github.com/precice/precice/blob/6cb67dd1478b79aff87cfcc12e63df19ad9dca9f/src/mesh/Mesh.hpp#L38

has now actually much associated functionality:

(0) computation in 
https://github.com/precice/precice/blob/6cb67dd1478b79aff87cfcc12e63df19ad9dca9f/src/mesh/Mesh.cpp#L210

(1) merging in
https://github.com/precice/precice/blob/6cb67dd1478b79aff87cfcc12e63df19ad9dca9f/src/partition/ReceivedPartition.cpp#L461

(2) intersection in 
https://github.com/precice/precice/blob/6cb67dd1478b79aff87cfcc12e63df19ad9dca9f/src/partition/ReceivedPartition.cpp#L448

(3) testing whether it contains a specific vertex
https://github.com/precice/precice/blob/6cb67dd1478b79aff87cfcc12e63df19ad9dca9f/src/partition/ReceivedPartition.cpp#L507

(4) an own communication wrapper class
https://github.com/precice/precice/blob/develop/src/com/CommunicateBoundingBox.hpp

It's time to bundle most of this functionality ( (1)-(3) yes, (4) no, (0)? my first suggestion) in a separate class within the `mesh` package.
Which relation to implement to `Mesh` needs careful consideration, meaning does a `BoundingBox` have a reference to a `Mesh`?

**Comment by fsimonis** [comment]
To simplify sending and receiving bounding boxes, it would be helpful to implement it in terms of  `std::vector<double>` (instead of pairs) and provide access to the underlying data via
```
double const * BoundingBox::data() const;
```
Also creating a BoundingBox from a `std::vector<double>` would be handy for receiving. Maybe in some static factory function:
```
static BoundingBox fromData(std::vector<double> d);
```

To simplify logging, we should also provide a
```
std::ostream& operator<<(std::ostream & out, Boundingbox const & val);
```

In addition to that, the dimension will always be 2 or 3, thus the vector will never surpass 6 elements. So if we save `int dimension` + `std::array<double. 6>` the size of an BoundingBox object is only 52 Bytes. This would allow for a very dense representation and further simplify communication.

**Comment by oguzziya** [comment]
Should `Mesh::computeBoundingBox()` functionality implemented in `BoundingBox` class? If this is the case, `BoundingBox` should have a reference to the belonging mesh. If we do not want a reference to mesh, we can find bounds in the `Mesh::computeBoundingBox()` and we can pass only the bounds to `BoundingBox`

**Comment by fsimonis** [comment]
@oguzziya The bounding box really only cares about coordinates and its dimension. So the interface should probably be implemented based on the coordinate type `Eigen::VectorXd`.

Computing the boundingbox in the Mesh class should really be something as simple as this:
```cpp
void Mesh::computeBoundingBox()
{
  BoundingBox bb(_dimensions);
  for (auto const & v: _vertices) {
    bb.expandTo(v.getCoords());
  }
  _bb = bb;
}
```
It could even be a one-liner if you use `std::accumulate` (good old Monoids).
