### ISSUE TITLE
AlwaysBuild(symlink) does not work as expected

### ISSUE THREAD

**Issue by uekerman** [precice/precice#75]
When I run e.g. `scons compiler=mpicxx staticlib  -j4` the symlink gets not updated. 
Also, in
```
symlink = env.Command(
    target = "symlink",
    source = None,
    action = "ln -fns {0} {1}".format(os.path.split(buildpath)[-1], os.path.join(os.path.split(buildpath)[0], "last"))
)
```
`symlink` in  target = "symlink" should be start with a lower case s, but that fix does not solve our problem.

Aren't we just in the situation described at the bottom of [this page](http://www.scons.org/doc/0.97/HTML/scons-user/x1030.html)?

**Comment by floli** [comment]
When running ```scons compiler=mpicxx staticlib -j4``` the symlink should be updated! Did you maybe explicitly state a target like ```scons solib```? Then the symlink will not be updated.

I am aware of that behavior, but with scons I got no idea how to fix it. The ```AlwaysBuild``` is set for the symlink, but it`s meaning is that the target is always considered out of date when built, but not that this target is always built.

**Comment by uekerman** [comment]
> When running scons `compiler=mpicxx staticlib -j4` the symlink should be updated! Did you maybe explicitly state a target like `scons solib`? Then the symlink will not be updated.
For me, it gets no updated, but `staticlib` is the explicit target here or what do you mean exactly? 

So, basically, `AlwaysBuild` does not do what we want. Is there any functionality that can solve our problem? i.e. always update the symlink independent of which targets we built?

**Comment by floli** [comment]
When running just ```scons```, without any targets, all targets are built, that includes symlink. When running e.g. ```scons staticlib``` only staticlib is built, which excludes symlink. AlwaysBuild says that the target should be rebuilt every time, i.e. is considered dirty, but only if it should be built, i.e. is named on the command line.

You are correct, AlwaysBuild does not do what we want (it does something we want, but not what the issue is about here) and I got no idea how to make scons to really always build the target.
