### ISSUE TITLE
Factor out numerical helper functions

### ISSUE THREAD

**Issue by floli** [precice/precice#8]
This is a request for discussion.

In order to get rid of the tarch package I propose to factor out numerical helper function to a new ```numerics``` package.

This includes functions like:
* ```tarch::la::norm2```
* ```tarch:la::dot```
* Maybe the updatedQR stuff. That needs to discussed with @scheufks.
* Functions like ```tarch::la::equals```

Stuff in that package should really concentrate on the numerics and should be independent as far as possible.

**Comment by davidsblom** [comment]
If you'd like to get rid of the tarch package, you could try to use the Eigen API. There is a `.norm()` and `.dot()` method for vectors. The `tarch::la::equals` I would actually try to avoid to use though.

**Comment by floli** [comment]
For Eigen objects we would of course use the member functions. Though it will still take some time to purge all tarch vectors from precice we need to keep tarch for some time.
How would you do floating point comparisions with zero e.g. instead?

**Comment by davidsblom** [comment]
Ah ok. I would try to avoid divisions completely, and use multiplications as much as possible. Of course that's not always possible.

**Comment by uekerman** [comment]
several comments:
* we cannot get rid of comparisons of floats with 0, since we need such functionality for the geometrical queries ("is the node inside outside or on the circle"). divisions we usually already try to avoid whenever possible
* yes, we should try to get rid of tarch as much as possible and use eigen functionality instead, step by step
* i would go one step further and do a "parallel(numerics)" package, where all master-slave related functionality lies. at the moment this is just some static class MasterSlave in utils. all numerics functionality, like dot or norm2 could be implemented there (e.g. based on eigen for each partition). updatedQR would then not go there as it only relies on simple building blocks, like dot.  
* not sure where to put "equals" then

**Comment by floli** [comment]
Closing this, as per discussion yesterday the the idea was discarded.
