### ISSUE TITLE
Check unconditional read mapping in initializeData

### ISSUE THREAD

**Issue by fsimonis** [precice/precice#834]
`initializeData()` contains an unconditional write mapping. Why?

https://github.com/precice/precice/blob/98b09c8fd184726530c33b23d6400d4ff1cf6d02/src/precice/impl/SolverInterfaceImpl.cpp#L336-L338

In `advance` we have such a condition

https://github.com/precice/precice/blob/a53645cc7bc2ad0a9abba51a1aecbca64aa4022a/src/precice/impl/SolverInterfaceImpl.cpp#L411-L415

Connected to this is the question whether `initializeData` should be called even if no data needs to be initialized (we currently explain it that way in the adapter example)? If yes, how do we treat the mappings there then?

Related to #824

**Comment by uekerman** [comment]
@BenjaminRodenberg Did we maybe solve this on-the-fly already?

**Comment by BenjaminRodenberg** [comment]
> `initializeData()` contains an unconditional write mapping. Why?

I think because the check `willDataBeExchanged` that we usually apply in `advance()` would always give us true in `initializeData()`. The question we have to ask here is not "are we at the end of the time window?", but "does the exchanged data have `initialize="true"` in the configuration?". We could solve this by exposing `BaseCouplingScheme::sendsInitializedData()`. @uekerman what do you think? Does this make sense?

(If we have several pieces of write data, some being initialized, some not, it becomes more complicated, but let's not open this box, because `isActionRequired(writeInitialData)` also does not work on the basis of single pieces of data. I think it's also consistent to just map all write data, even if only one write data actually would need this.)

**Comment by BenjaminRodenberg** [comment]
Another note, if we want to add a check: I think we make our lives easier, if we put the check into `v3.0.0`. With the old `initialize` + `initializeData` API from `v2` it's more complicated and I think it's not really a critical thing to fix.

**Comment by uekerman** [comment]
> We could solve this by exposing BaseCouplingScheme::sendsInitializedData(). @uekerman what do you think? Does this make sense?

Yes, I think this would be the right way to go.

> I think we make our lives easier, if we put the check into v3.0.0

Agree. Let's do it then. Pushing to the next milestone.
