### ISSUE TITLE
Inform user about unavailable log levels

### ISSUE THREAD

**Issue by fsimonis** [precice/precice#860]
**Please describe the problem you are trying to solve.**
In release builds of preCICE, the `DEBUG` and `TRACE` log levels are not available as they are not compiled into the library.

Let's assume, a user defines the following log sink:
```xml
<log>
  <sink filter="(%Severity% >= debug)" />
</log> 
```

Then the expectation will be to see debug output, but it won't be visible in release builds.
There will also be no notification of why this is the case, which can confuse users. It also makes support more difficult.

This problem affects all users of our binary packages.

**Describe the solution you propose.**
Print an info statement if debug or trace log was requested in a release build.
Proposition:
```
INFO: You requested debug or trace output, which is not available in this release build of preCICE. Use a debug build if you require these log levels.
```

**Describe alternatives you've considered**
Silently ignore it.

**Comment by MakisH** [comment]
Maybe then it makes sense to also ship binary packages built in Debug mode. At the end of the day, a user that uses binary packages most probably is developing a simulation on a laptop and wants to have such output. Since these packages are not in any distribution repositories, we don't need to stick with the "production == release mode" rule, or we can distribute both.

**Comment by fsimonis** [comment]
@MakisH Swapping the packages to the debug version will lead to problems with package managers and confuse users.
Shipping both release and debug versions in the same package, hover is a good idea. CMake has build-in support for selecting libraries based on the build type. So this would be completely transparent for CMake users of preCICE.

**Comment by MakisH** [comment]
@fsimonis I am talking about the packages we upload on GitHub with every release. How will this confuse users more than currently, when they cannot enable debug output when they almost certainly need it at some point? Is there any package manager actually using these packages (apart from when manually installing them with APT)? What kind of problems would that cause?

I am not sure what you mean shipping both in the same package. Something like `/usr/lib/libprecice2.1.0_debug.so` and `/usr/lib/libprecice2.1.0.so`?

What I mean is simply generating both Release and Debug packages and uploading them both on GitHub. I do prefer to keep the release version as default (since it is the common practice) and keep improving preCICE so that one day a user never needs to enable debug output.

**Comment by fsimonis** [comment]
> How will this confuse users more than currently, when they cannot enable debug output when they almost certainly need it at some point?

Packages are normally release versions. Debug versions are separate suffixed packages [more info]( https://wiki.debian.org/DebugPackage).

Our instructions require the user to switch between release and debug versions. The only way of supporting this is by providing a package that contains both versions. Or we have to be clear that the user should not use the release version of the library until they run the simulation on a system. Problem here is that our debug builds are very slow.

> I am not sure what you mean shipping both in the same package. Something like /usr/lib/libprecice2.1.0_debug.so and /usr/lib/libprecice2.1.0.so?

* `/usr/libprecice.so.2.1.0` for the release
* `/usr/libprecice_dbg.so.2.1.0` for the debug build

CMake can automatically switch between them based on the build type used by the calling project.

**Comment by MakisH** [comment]
Then it looks like there is already a standard way to handle this, perfect! :-)

**Comment by fsimonis** [comment]
We could add a line to the following part:

https://github.com/precice/precice/blob/00589fe951f9715174eafbd66657294e0d8eb8e4/src/precice/impl/SolverInterfaceImpl.cpp#L164-L167
