### ISSUE TITLE
Solverdummy hangs

### ISSUE THREAD

**Issue by eugeneswalker** [precice/precice#867]
I'm trying to run `solverdummy C example` inside a Docker container.
* `precice 2.1.0`
* `Ubuntu 18.04`
* `x86_64`
* `GCC 7.5.0`

The solverdummy c example builds fine. The problem is nothing seems to happen when I run, in two separate terminals:

<b>Terminal 1</b>
```
$> ./solverdummy ../precice-config.xml SolverOne MeshOne
DUMMY: Running solver dummy with preCICE config file "../precice-config.xml", participant name "SolverOne", and mesh name "MeshOne".
preCICE: This is preCICE version 2.1.0
preCICE: Revision info: no-info [Git failed/Not a repository]
preCICE: Configuring preCICE with configuration "../precice-config.xml"
preCICE: I am participant "SolverOne"
preCICE: Setting up master communication to coupling partner/s
... <nothing happens here, indefinite hang>
```

<b>Terminal 2</b>
```
$> ./solverdummy ../precice-config.xml SolverTwo MeshTwo
DUMMY: Running solver dummy with preCICE config file "../precice-config.xml", participant name "SolverTwo", and mesh name "MeshTwo".
preCICE: This is preCICE version 2.1.0
preCICE: Revision info: no-info [Git failed/Not a repository]
preCICE: Configuring preCICE with configuration "../precice-config.xml"
preCICE: I am participant "SolverTwo"
preCICE: Setting up master communication to coupling partner/s
... <nothing happens here, indefinite hang>
```

Any ideas?

**Comment by MakisH** [comment]
Thank you for reporting this, @eugeneswalker!

Hopefully [this troubleshooting page](https://github.com/precice/precice/wiki/Problems-with-Establishing-the-Communication) helps.

What is happening is that the one participant creates a directory `precice-run/` which contains its address and the other participant is looking for this directory. Since you are running from a Docker container, do both sides have read/write access to the path where you start `solverdummy` from? (just in case you start the two terminals from different containers accidentally)

Is there anything that could block the network connection from the one to the other participant? If you are starting in different containers, you need to allow them to interact (e.g. [with docker-compose](https://github.com/precice/systemtests/blob/develop/docs/architecture.md#running-tests)).

**Comment by eugeneswalker** [comment]
I looked at the Troubleshooting page you linked to and it looks like my problem was `Problem 3: Dirty files from last run` as detailed in the Troubleshooting page. When I deleted `precise-run` folder from previous run, and re-tried, it worked! Thank you for your quick response!

**Comment by MakisH** [comment]
Nice! :-D

To keep a better overview of open issues, you can also write on the preCICE forum: https://precice.discourse.group/
We all (+ more people) read and answer also there.
