### ISSUE TITLE
Compilation Failure 

### ISSUE THREAD

**Issue by bmanga** [precice/precice#89]
I was trying to compile precice with the following command:
``CPLUS_INCLUDE_PATH="/usr/include/eigen3" scons petsc=false mpi=false python=false -j 8``
but I got the following error:

```
In file included from /usr/include/boost/test/unit_test.hpp:19:0,
                 from src/testing/Testing.hpp:5,
                 from src/cplscheme/boosttests/PreconditionerTest.cpp:9:
src/cplscheme/boosttests/PreconditionerTest.cpp:261:42: error: ‘MasterComFixture’ is not a member of ‘precice::testing’
     * boost::unit_test::fixture<testing::MasterComFixture>()){
                                          ^
```
I can trigger the error with:
```
g++ -o build/debug-nopetsc-nompi-nopython/cplscheme/boosttests/PreconditionerTest.o -c -Wall -std=c++11 -fPIC -g3 -O0 -DPRECICE_NO_PETSC -DEIGEN_INITIALIZE_MATRICES_BY_NAN -DBOOST_SPIRIT_USE_PHOENIX_V3 -DBOOST_ALL_DYN_LINK -DPRECICE_NO_MPI -DPRECICE_NO_PYTHON -Isrc src/cplscheme/boosttests/PreconditionerTest.cpp -I/usr/include/eigen3
```
Tested on:
Ubuntu 17.10
g++ 7.2.0
boost 1.62.0.1
eigen 3.3.4-3

**Comment by floli** [comment]
The problem happens only when compiling with ```mpi=off```, because MasterComFixture is not compiled then.
Could you work around that and use MPI?
To fix that:
+ MasterComFixture should be existing and empty when compiling without MPI
+ Tests that require MPI should have the testing::OnSize(4) decorator attached or use ```#ifndef PRECICE_NO_MPI```

**Comment by BenjaminRueth** [comment]
See 75653d72dbb2eb0bf7b2d103c9d415ed6cc9e900 for a fix. As soon as Travis has run through successfully I will merge back into develop.

If you want to make sure that you do not get any compilation errors, you should use the preCICE release (https://github.com/precice/precice/releases/tag/v1.0.0) instead of the develop branch here on github. The release is well tested. Using develop is only recommended, if you rely on features that are not included in the release yet.

**Comment by bmanga** [comment]
That worked, thanks!
