### ISSUE TITLE
GMRES cannot deal with consistent RBF mapping using constant input data 

### ISSUE THREAD

**Issue by uekerman** [precice/precice#904]
**Describe your setup**

Only happens sometimes, for example in the docker container provided here: https://github.com/dealii/code-gallery/pull/84#issuecomment-723416669

**Describe the problem**

For constant input data, a consistent RBF mapping with separated polynomial can lead to an apparently ill-conditioned (?) system, GMRES cannot cope with. 

A * x = b

with b very small, around machine precision, but not 0 yet. 

<details>
  <summary>PETSc output</summary>
  
  ```bash
PETSc GMRES:

KSP Object: Coefficient Solver (solverC_) 1 MPI processes
  type: gmres
    restart=30, using Classical (unmodified) Gram-Schmidt Orthogonalization with no iterative refinement
    happy breakdown tolerance 1e-30
  maximum iterations=10000, nonzero initial guess
  tolerances:  relative=1e-09, absolute=1e-50, divergence=10000.
  left preconditioning
  using PRECONDITIONED norm type for convergence test
PC Object: (solverC_) 1 MPI processes
  type: icc
    out-of-place factorization
    0 levels of fill
    tolerance for zero pivot 2.22045e-14
    using Manteuffel shift [POSITIVE_DEFINITE]
    matrix ordering: natural
    factor fill ratio given 1., needed 1.
      Factored matrix follows:
        Mat Object: 1 MPI processes
          type: seqsbaij
          rows=6, cols=6
          package used to perform factorization: petsc
          total: nonzeros=21, allocated nonzeros=21
          total number of mallocs used during MatSetValues calls=0
              block size is 1
  linear system matrix = precond matrix:
  Mat Object: C 1 MPI processes
    type: seqsbaij
    rows=6, cols=6
    total: nonzeros=21, allocated nonzeros=21
    total number of mallocs used during MatSetValues calls=0
        block size is 1
---[precice] ERROR:  The linear system of the RBF mapping from mesh boundary-mesh to mesh dealii-mesh has not converged. This means most probably that the mapping problem is not well-posed. Please check if your coupling meshes are correct. Maybe you need to fix axis-aligned mapping setups by marking perpendicular axes as dead?
  ```
</details>

**Solution**

Unclear yet. We need to better understand the problem first. Is it the preconditioner? Playing around with the PETSc settings could shed some light on this.

**Comment by DavidSCN** [comment]
Some additional information:

> Only happens sometimes, for example in the docker container provided here: dealii/code-gallery#84 (comment)

Happens every time preCICE uses petsc for the mapping computation. In the linked comment, I used a preCICE version with `PETSC=OFF` so that the actual problem was not faced. I was able to reproduce it on recent Ubuntu systems.

The reason, why the computation fails is that we explicitly specify a non-zero initial guess in the petsc Krylov solver configuration: 

https://github.com/precice/precice/blob/44af0f53402575974c273c2b39acc2966e601004/src/mapping/PetRadialBasisFctMapping.hpp#L558-L564

This way, petsc doesn't check, if the initial RHS is zero or not. Removing the respective line from the solver configuration and using the default configuration (initial guess is zero) resolves the problem. However, as mentioned in the comment, the non-zero initial guess has probably some sense and also the petsc related mapping test fails with the following message:
```bash
error: in "MappingTests/PetRadialBasisFunctionMapping/Serial/SolutionCaching": check its == 0 has failed [2 != 0]
8: (0) 19:14:07 [mapping::PetRadialBasisFctMapping]:586 in computeMapping: WARNING: RBF rescaling linear system has not converged. Deactivating rescaling!
```

Another aspect: the problem doesn't need to be fully constant in order to trigger the issue, it is sufficiently to be 'constant enough'. In the example, we map in total 6 values from the boundary participant to our solver, where we pass one specific time step with all 6 values being exactly the same. However, changing one specific value by a magnitude of 10^{-5} (far beyond machine precision) still triggers the same issue.

**Comment by uekerman** [comment]
The failing test is this one
https://github.com/precice/precice/blob/908cf7ae1a7e8d4a5bfa9e0088d8cf8f3ca3fd36/src/mapping/tests/PetRadialBasisFctMappingTest.cpp#L1949

The PETSc documentation: 
https://www.mcs.anl.gov/petsc/petsc-current/docs/manualpages/KSP/KSPSetInitialGuessNonzero.html

I guess we need a PETSc option to say that we want to set an initial guess, which could also be zero. If there is not such an option available we could also do this manually (setting the flag only if the rhs is indeed non-zero). 

Could also be a question for the PETSc mailing list?
