### ISSUE TITLE
error in SU2 + preCICE (ubuntu)

### ISSUE THREAD

**Issue by 3rav** [precice/precice#96]
Hi,

I've compiled:
- preCICE
- CalculiX + preCICE adapter
- standard version of SU2

but I have error while compiling the SU2 + preCICE adapter:

![su2_error](https://user-images.githubusercontent.com/24394573/35152880-7d40f4ba-fd24-11e7-82a6-15e82475c1b6.png)

```
/usr/local/PRECICE_ROOT/src/cplscheme/CompositionalCouplingScheme.cpp:480: undefined reference to `boost::log::v2_mt_posix::core::get_global_attributes() const'
```

other part:

```
`/usr/local/PRECICE_ROOT/src/cplscheme/CompositionalCouplingScheme.cpp:485:` undefined reference to `boost::log::v2_mt_posix::attribute_set::~attribute_set()'
/usr/local/PRECICE_ROOT/build/last/libprecice.a(CompositionalCouplingScheme.o):/usr/local/PRECICE_ROOT/src/cplscheme/CompositionalCouplingScheme.cpp:485: more undefined references to `boost::log::v2_mt_posix::attribute_set::~attribute_set()' follow
/usr/local/PRECICE_ROOT/build/last/libprecice.a(CompositionalCouplingScheme.o): In function `__static_initialization_and_destruction_0(int, int)':
/usr/include/boost/system/error_code.hpp:221: undefined reference to `boost::system::generic_category()'
/usr/include/boost/system/error_code.hpp:222: undefined reference to `boost::system::generic_category()'
/usr/include/boost/system/error_code.hpp:223: undefined reference to `boost::system::system_category()'
/usr/local/PRECICE_ROOT/build/last/libprecice.a(MultiCouplingScheme.o): In function `precice::cplscheme::MultiCouplingScheme::initialize(double, int)':
/usr/local/PRECICE_ROOT/src/cplscheme/MultiCouplingScheme.cpp:47: undefined reference to `boost::log::v2_mt_posix::core::get()'
```

PS. I used UBUNTU 17.10 and the BOOST liubrary are from: apt-get install libboost-dev

Regards
Rafal

**Comment by uekerman** [comment]
Hi Rafael,

This appears to be a linking error. Your boost version 1.62 is sufficient (also preCICE compiles). I assume you use the static preCICE library `libprecice.a` to link? A possible solution is probably to use the dynamic library `libprecice.so`. But still, also the static linking should work.

@arusch Alex, can you help? Where do you specify which libraries are linked? I didn't find this in the su2-adapter. Or have we always only built SU2 with the dynamic preCICE lib?

Btw, such questions are probably better asked on our [mailing list](https://mailman.informatik.uni-stuttgart.de/mailman/listinfo/precice). More people can help you there and more people see a possible answer (they might have the same problem). 

Benjamin

**Comment by arusch** [comment]
Hi Rafael,

by default the adapted SU2_CFD module links against the dynamic preCICE library.

I have had similar problems before and in almost all cases the boost libraries were not linked correctly during compilation of preCICE. So this would be my first idea of what might cause the problem.
Does `ldd libprecice.so` show that, indeed, all boost libraries are linked correctly?
If so, have you set the `PRECICE_ROOT` variable correctly in your environment?
Have you set the SU2 environment variables as suggested at the end of the configuration step (when building the standard version of SU2)?

If all of the above does not help nor indicate what the problem is, please change the following in `$SU2_HOME/SU2_CFD/obj/Makefile.am`:
Modify `libSU2Core_libadd = $(PRECICE_ROOT)/build/last/libprecice.a` to `libSU2Core_libadd =`. Then `cd $SU2_HOME` and run `autoreconf`. Afterwards `make clean` and build again with the options of your choice, i.e. rerun the SU2 configuration and make steps. The static preCICE-library dependency is not strictly necessary for running the SU2_CFD module but is included for completeness of the SU2 core.

Best
Alexander

**Comment by 3rav** [comment]
Hello,
I confirm, the problem was the lack of libprecice.so library

Thank you for your help.

**Comment by uekerman** [comment]
Perfect, happy to hear that!
