### ISSUE TITLE
error undefined reference to `pthread_create' and compile success but run fail

### ISSUE THREAD

**Issue by num44** [precice/precice#979]
**Describe your setup**

Operating system (e.g. Linux distribution and version): CentOS Linux release 7.6.1810
preCICE Version: 2.2.0

**Describe the problem**

I am trying  to install preCICE2.2.0 coupling with OpenFOAM6.0 and deal_ii in cluster without root. I install all from source code and add 'set' statements in CMakeLists.txt to locate EIGEN3 and LIBXML2 where I install because the environment variables in .bashrc seem useless.

```
set(EIGEN3_INCLUDE_DIR "/vol2/home/wjm/libs/eigen-3.3.9")
set(LIBXML2 "/vol2/home/wjm/libs/libffi-python")
set(LIBXML2_LIBRARIES "/vol2/home/wjm/libs/libffi-python/lib/libxml2.so")
set(LIBXML2_INCLUDE_DIR "/vol2/home/wjm/libs/libffi-python/include/libxml2")
```

and set some cxx flaps in CMakeLists.txt after 'find_package(MPI REQUIRED)' according to the cluster usage
```
set(CMAKE_C_FLAGS "-g -I/opt/ohpc/pub/mpi/mvapich2-gnu8/2.3.1/include -L/opt/ohpc/pub/mpi/mvapich2-gnu8/2.3.1/lib -Wl,-rpath -Wl,/opt/ohpc/pub/mpi/mvapich2-gnu8/2.3.1/lib -Wl,--enable-new-dtags -lmpi -m64")
set(CMAKE_CXX_FLAGS "-g -I/opt/ohpc/pub/mpi/mvapich2-gnu8/2.3.1/include -L/opt/ohpc/pub/mpi/mvapich2-gnu8/2.3.1/lib -lmpicxx -Wl,-rpath -Wl,/opt/ohpc/pub/mpi/mvapich2-gnu8/2.3.1/lib -Wl,--enable-new-dtags -lmpi -std=c++11 -m64")
```

I configure with this command 
`cmake -DBUILD_SHARED_LIBS=ON -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=~/software/preCICE -DPRECICE_MPICommunication=ON -DPRECICE_PETScMapping=ON -DPRECICE_InstallTest=ON -DPRECICE_PythonActions=OFF -DPRECICE_CTEST_MPI_FLAGS="-g $(MPI_ARCH_INC) $(MPI_ARCH_LIBS) -lmpicxx -Wl,-rpath -Wl,$(MPI_ROOT)/lib -Wl,--enable-new-dtags -lmpi -lpthread -std=c++11 -m64"`

and the result is that
[configure.log](https://github.com/precice/precice/files/6161095/configure.log)

It seems is good. But CMakeFiles/CMakeError.log shows some errors.
[CMakeError.log](https://github.com/precice/precice/files/6161101/CMakeError.log)

and then make and make install are all fine, no any error occurs.

In ctest,  24 tests failed out of 29, and in make test_install it is good.
[ctest.log](https://github.com/precice/precice/files/6161114/ctest.log)
[make test_install.log](https://github.com/precice/precice/files/6161115/make.test_install.log)

After installing adapters, I run the tutorials case flap_perp_2D/OpenFOAM-deal.II, and some errors occur in fluid part. It seems to be memory access out of range. There is 16G memory in one node of this cluster, and I don't think it needs more than 16G to run this case.
[Fluid.log](https://github.com/precice/precice/files/6161159/Fluid.log)
[Solid.log](https://github.com/precice/precice/files/6161161/Solid.log)

Am I install the preCICE correctly?

**Step To Reproduce**
1. cmake -DBUILD_SHARED_LIBS=ON -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=~/software/preCICE -DPRECICE_MPICommunication=ON -DPRECICE_PETScMapping=ON -DPRECICE_InstallTest=ON -DPRECICE_PythonActions=OFF -DPRECICE_CTEST_MPI_FLAGS="-g $(MPI_ARCH_INC) $(MPI_ARCH_LIBS) -lmpicxx -Wl,-rpath -Wl,$(MPI_ROOT)/lib -Wl,--enable-new-dtags -lmpi -lpthread -std=c++11 -m64
2. make -j 6
3. ctest
4. make install
5. make test_install

Thanks.

**Comment by fsimonis** [comment]
For the record:
Compiler is GCC 8.3.0
MPI Impl is MVAPICH2 Version: 2.3.1 (gcc wrappers)

---

Hi, interesting to see an MVAPICH2 user!

Most important is that `test_install` works, hence the install is _most likely_ working.

CMake's [FindMPI](https://cmake.org/cmake/help/v3.13/module/FindMPI.html) should handle the majority of the manual work for you. Try setting the compiler to the MPI compiler wrapper by setting it in your .bashrc (for consistency). Something like this:
```bash
export CXX=mpicxx
export CC=mpicc
```
The compiler flags will be deduced from the wrapper. Specifying further compiler flags should not be necessary.

Instead of setting the Eigen3 include directory in the CMakeLists, please use the env instead:
```bash
# set(EIGEN3_INCLUDE_DIR "/vol2/home/wjm/libs/eigen-3.3.9")
export Eigen3_ROOT=/vol2/home/wjm/libs/eigen-3.3.9
```

Also libxml2 is a very common library and present on many deployments. CMake should be able to detect it without any user intervention. See the packages [libxml2-devel](https://centos.pkgs.org/7/centos-x86_64/libxml2-devel-2.9.1-6.el7.5.x86_64.rpm.html) and [libxml2](https://centos.pkgs.org/7/centos-x86_64/libxml2-2.9.1-6.el7.5.x86_64.rpm.html) for file locations.

It is always helpful to double check the env by `echo $Eigen3_ROOT` before configuring preCICE.

The tests are failing due to the misinterpretation of `PRECICE_CTEST_MPI_FLAGS`.
Our tests run on 4 MPI ranks and these additional flags are passed to `mpiexec`, hence the failing tests.
This is useful in cases where one needs to pass flags such as OpenMPI `--oversubscribe` running on dual core machines.

Another way of installing preCICE is our [spack package](https://www.precice.org/installation-spack.html).

Hope that helps!

**Comment by fsimonis** [comment]
Closing as no reply
